### ISSUE TITLE
Not working after upgrading from Ubuntu 17.04 to 17.10

### ISSUE THREAD

**Issue by oshihirii** [LordAmit/Brightness#100]
OS: Linux
Distro: Ubuntu 17.10
output of `xrandr -q`

> Screen 0: minimum 320 x 200, current 2360 x 1920, maximum 8192 x 8192
> XWAYLAND0 connected 1280x1024+1080+0 (normal left inverted right x axis y axis) 380mm x 300mm
>    1280x1024     59.89*+
> XWAYLAND1 connected 1080x1920+0+0 (normal left inverted right x axis y axis) 510mm x 290mm
>    1080x1920     59.96*+

Version of Brightness Controller:  Brightness Controller v2.0 build 1

Description:

Moving the controls does not cause any adjustment in brightness.

**Comment by LordAmit** [comment]
Hmm,

Apparently, wayland is not compatible with xrandr.

**Comment by oshihirii** [comment]
Hello,

Are there any plans to make Brightness Controller compatible with Ubuntu 17.10?  

Based on simple google searches around "Ubuntu 17.10 screen brightness" I can't find any resources addressing the issue.  

Thank You.

**Comment by LordAmit** [comment]
That depends. 
I still do not know how the brightness can be controlled in Ubuntu 17.10 Wayland server. Hopefully, it will have an interface similar to xrandr.  If it does have one like this, I should be able to create a different version for Ubuntu 17.10 (as a workaround) in a weekend or two.

**Comment by FeniksFire** [comment]
@oshihirii If you need then Brightness Controller is compatible with x11, you can change from Wayland to X11 in Ubuntu 17.10, just reboot and change in log panel from Ubuntu to Ubuntu on Xorg.
![zrzut ekranu z 2017-10-30 19-24-35](https://user-images.githubusercontent.com/13856703/32188978-9dfbc6c2-bda9-11e7-89ac-3d25c9942250.png)
.

**Comment by AdamKane41** [comment]
a sloppy way to do it, using transparent layers...

![screenshot from 2017-12-19 09-41-41](https://user-images.githubusercontent.com/30092603/34162433-b17053a2-e4a1-11e7-89ce-0467857172f5.png)
