### ISSUE TITLE
Add "Ubuntu Bionic Beaver" to PPA

### ISSUE THREAD

**Issue by AdamKane41** [LordAmit/Brightness#103]
OS: Ubuntu
Distro: Bionic Beaver (development branch) x86_64
Version of Brightness Controller: 2

Can we have PPA for ubuntu 18.04 on "launchpad.net/~apandada1" please?

**Comment by apandada1** [comment]
Done. Thanks for reminding us.

**Comment by apandada1** [comment]
Please check and report whether it works.

**Comment by AdamKane41** [comment]
thanks.
both "brightness-controller (2.0.2)" and "brightness-controller-simple (1.2.3)" install & run with updated PPA. running 18.04 on real machine
