### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by AdamKane41** [LordAmit/Brightness#104]
"about.py" reads: "_Brightness Controller v2.0 build 1_" but should say  "_Brightness Controller v2.0.2_" . to  match version  from apt in terminal

**Comment by apandada1** [comment]
We have to release a new version to change the version number 😂

**Comment by AdamKane41** [comment]
guess im a n00bsib0t..got confused by:
![screenshot from 2017-12-30 08-24-33](https://user-images.githubusercontent.com/30092603/34454533-4acff920-ed3b-11e7-9ac7-5f1d1eb5fb21.png)

sorry

**Comment by apandada1** [comment]
We will do it when a new version is released after new features are implemented.

On Dec 30, 2017 7:02 PM, "AdamKane" <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #104<https://github.com/LordAmit/Brightness/issues/104>.
