### ISSUE TITLE
FIX controller: not all text fits on HiDPI screens

### ISSUE THREAD

**Issue by allanlaal** [LordAmit/Brightness#106]
OS: Ubuntu Mate 16.04 LTS
Version of Brightness Controller: 2.0.2

	allan@L4:~$ xrandr -q
	Screen 0: minimum 8 x 8, current 5760 x 1620, maximum 32767 x 32767
	eDP1 connected primary 2880x1620+2880+0 (normal left inverted right x axis y axis) 340mm x 190mm
	   2880x1620     59.96*+  47.97  
	   2048x1536     60.00  
	   1920x1440     60.00  
	   1856x1392     60.01  
	   1792x1344     60.01  
	   2048x1152     60.00  
	   1920x1200     59.95  
	   1920x1080     60.00    59.93  
	   1600x1200     60.00  
	   1680x1050     59.95    59.88  
	   1600x1024     60.17  
	   1400x1050     59.98  
	   1600x900      60.00  
	   1280x1024     60.02  
	   1440x900      59.89  
	   1280x960      60.00  
	   1440x810      60.00  
	   1368x768      60.00  
	   1360x768      59.80    59.96  
	   1152x864      60.00  
	   1280x720      60.00  
	   1024x768      60.00  
	   1024x576      60.00  
	   960x540       60.00  
	   800x600       60.32    56.25  
	   864x486       60.00  
	   640x480       59.94  
	   720x405       60.00  
	   640x360       60.00  
	DP1 disconnected (normal left inverted right x axis y axis)
	DP2 disconnected (normal left inverted right x axis y axis)
	HDMI1 connected 2880x1620+0+0 (normal left inverted right x axis y axis) 293mm x 165mm
	   1920x1080     59.72*+  60.00    59.94  
	   1920x1080i    60.00    50.00    59.94  
	   1680x1050     59.88  
	   1280x1024     60.02  
	   1440x900      59.90  
	   1280x800      59.91  
	   1152x864      59.97  
	   1280x720      60.00    50.00    59.94  
	   1024x768      60.00  
	   800x600       60.32  
	   720x576       50.00  
	   720x480       60.00    59.94  
	   640x480       60.00    59.94  
	HDMI2 disconnected (normal left inverted right x axis y axis)
	VGA1 disconnected (normal left inverted right x axis y axis)
	VIRTUAL1 disconnected (normal left inverted right x axis y axis)
	eDP-1-2 disconnected (normal left inverted right x axis y axis)
	DVI-D-1-1 disconnected (normal left inverted right x axis y axis)

see image:
![screenshot at 2018-02-03 08 27 06](https://user-images.githubusercontent.com/740826/35763789-78836d88-08bc-11e8-9a4b-d71ad728a219.png)

also, the font is a lot smaller than my system default

**Comment by allanlaal** [comment]
its not possible to take a screenshot of the Color Temperature dropdown, but all fields there are shortened to the point of not understanding what they are

**Comment by LordAmit** [comment]
Hi,
I really appreciate your efforts to point out this issue. Brightness Controller was created using PySide framework, which is reliant on QT4.8 - and has sketchy support on HiDPI resolution. 

I am still looking for a workaround  though. Meanwhile, can you try installing qt4-settings by the following command: 

`
sudo apt install qt4-qtconfig 
`
 Yeah, I know, different package and program name. Try changing the GUI settings and font there, maybe?

**Comment by allanlaal** [comment]
changing font in qt config has no effect on how the text is truncated in Color dropdown

**Comment by apandada1** [comment]
We are now using Qt5, which has great support for HiDPI. Is this issue still there? I don't see any problem on my HiDPI screen on KDE Neon.
