### ISSUE TITLE
Not working on my PC (maybe because of Wayland?)

### ISSUE THREAD

**Issue by matonga** [LordAmit/Brightness#107]
OS: Linux
Distro: Ubuntu 17.10 (artful)

output of `xrandr -q`
Screen 0: minimum 320 x 200, current 2732 x 781, maximum 8192 x 8192
XWAYLAND0 connected 1366x768+1366+0 (normal left inverted right x axis y axis) 410mm x 230mm
   1366x768      59.62*+
XWAYLAND1 connected 1366x768+0+13 (normal left inverted right x axis y axis) 410mm x 230mm
   1366x768      59.62*+

Version of Brightness Controller: 2.0.2

**Comment by LordAmit** [comment]
Please switch to xorg in the login screen.  Ubuntu 17.10 uses Wayland by default, which does not support brightness controlling through xrandr. :disappointed:

**Comment by AdamKane41** [comment]
Upcoming Ubuntu LTS release 18.04 drops wayland as the default and re-enables xorg as primary.
