### ISSUE TITLE
Brightness-controller-simple doesnt detect monitors

### ISSUE THREAD

**Issue by IAMtheIAM** [LordAmit/Brightness#112]
OS:  Linux mint 19
Distro: 
output of `xrandr -q`
```
Screen 0: minimum 8 x 8, current 6880 x 2560, maximum 16384 x 16384
DVI-I-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected primary 2560x1440+1440+160 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   1920x1080     60.00    59.94    50.00    29.97    25.00    23.98    60.00    50.04  
   1680x1050     59.95  
   1440x900      59.89  
   1440x576      50.00  
   1440x480      59.94  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-0 connected 1440x2560+0+0 left (normal left inverted right x axis y axis) 597mm x 336mm
   3840x2160     60.00 +  29.98  
   2560x1440     59.95* 
   1920x1200     59.88  
   1920x1080     60.00    59.94    50.00    23.98  
   1680x1050     59.95  
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected 1440x2560+4000+0 left (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   3840x2160     29.97  
   2048x1152     60.00  
   1920x1200     59.88  
   1920x1080     60.00    60.00    59.94    50.00    29.97    25.00    23.98  
   1680x1050     59.95  
   1600x900      60.00  
   1440x576      50.00  
   1440x480      59.94  
   1280x1440     59.90  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 connected 1440x2560+5440+0 right (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   3840x2160     29.97  
   2048x1152     60.00  
   1920x1200     59.88  
   1920x1080     60.00    60.00    59.94    50.00    29.97    25.00    23.98  
   1680x1050     59.95  
   1600x900      60.00  
   1440x576      50.00  
   1440x480      59.94  
   1280x1440     59.90  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
DP-5 disconnected (normal left inverted right x axis y axis)

```
Version of Brightness Controller-Simple: 
1.2.3

 `brightness-controller-simple` - it does not detect any displays at all.

**Comment by IAMtheIAM** [comment]
I'm not sure what you mean by primary? There are 3 displayport and 1 hdmi connection. One of the display ports is my center monitor, if that counts as primary.

**Comment by IAMtheIAM** [comment]
I tried again today and still "not found" for the simple edition.

**Comment by LordAmit** [comment]
Ah, found the bug. It was introduced somehow along the development and caused problem for exactly four monitor setup.

Changes has already been pushed to v1 branch. @apandada1 can you please check and confirm that it works at your end? 

If it does, please push it to PPA, thanks! :dancer: 

@IAMtheIAM - please wait for Archish to push the repo to PPA(if you are using PPA, that is) and let us know if this solves your problem :)

**Comment by apandada1** [comment]
I uploaded it to PPA

**Comment by LordAmit** [comment]
@IAMtheIAM please check by installing the latest version of the brightness controller simple and let us know if this solves your problem :dancer:

**Comment by IAMtheIAM** [comment]
It didn't work fully. Now the 2 monitors work, but it only shows 2. So it partially fixed it 

![not working bcs](https://user-images.githubusercontent.com/13709948/56449850-3d25ff80-62d4-11e9-8afd-240eaa442655.png)

**Comment by LordAmit** [comment]
Haha, I think I see the issue. Probably due to the different themes and DPIs it is being rendered incorrectly - hiding the bottom bars. By default it was supposed to show all four. 

Can you check and see if you can navigate to the bottom "invisible" bars using keyboard and changing the brightness? Of course, this is not a solution, but that'd allow us to confirm if my guess is right.

**Comment by IAMtheIAM** [comment]
Hello, actually yes I was able to Tab down and change the values using my arrow key, to the invisible bars, good guess.

**Comment by IAMtheIAM** [comment]
Hello @LordAmit Any updates on this? :-)

**Comment by apandada1** [comment]
Can we allow the window to be resized and make it remember its size?

**Comment by LordAmit** [comment]
Hello @IAMtheIAM, it is now evident that the old GUI components of Brightness Controller are not good enough for today's displays. We are also supposed to move onto PySide2, so I started working on rehauling the brightness controller's UI. 

Now, for you - I have a temporary solution. This will require you to comment out exactly one line in the brightness-controller file. Please find this line

```        
self.SetMaxSize((325, 138))
```

and make it like this:

```        
# self.SetMaxSize((325, 138))
```

Basically, we are now allowing it to have any size. This will allow you to change the size by using mouse. 

Or, you can set the desired value in that line at the 2nd number:

```        
# self.SetMaxSize((325, YOURVALUEHERE))
```

Saving it will make the change permanent for you. 
Both require saving the file and then starting the brightness-controller program again. 

Let us know if you have trouble finding the file. Depending on how you installed brightness controller - the file might end up in different places - so let us know how you installed it as well :dancer: 

@apandada1 Possible, but probably not a good choice.

**Comment by IAMtheIAM** [comment]
@LordAmit Hi, thanks. Where exactly would I look for the file containing `self.SetMaxSize((325, 138))`? I installed via the PPA

**Comment by apandada1** [comment]
/usr/bin/brightness-controller-simple

On Fri, May 24, 2019, 1:15 AM IAMtheIAM <notifications@github.com<mailto:notifications@github.com> wrote:

@LordAmit<https://github.com/LordAmit> Hi, thanks. Where exactly would I look for the file containing self.SetMaxSize((325, 138))? I installed via the PPA

**Comment by IAMtheIAM** [comment]
Hey, it worked! Commenting out that line allows resizing the window, and I can see all 4 sliders there now. So your fix is good, please feel free to add it to source. :-D

**Comment by wonderingabout** [comment]
phew
glad it works as i am considering using dual screen now
thanks for your software btw @LordAmit , my eyes thank you every day :1st_place_medal:

**Comment by LordAmit** [comment]
I am really grateful to know that this was helpful ❤️

**Comment by wonderingabout** [comment]
glad you like it, because i definitely use brightness controller everyday :100: 
saved my eyes and hope it will still !
thanks !
