### ISSUE TITLE
Not working with HDMI cable on Wayland

### ISSUE THREAD

**Issue by Kogam22** [LordAmit/Brightness#116]
OS: Linux
Distro: Ubuntu 18.04 LTS
output of `xrandr -q` : 
```bash
kogam22@home:~$ xrandr -q
Screen 0: minimum 320 x 200, current 1680 x 1050, maximum 8192 x 8192
XWAYLAND0 connected 1680x1050+0+0 (normal left inverted right x axis y axis) 480mm x 300mm
   1680x1050     59.85*+
```
Version of Brightness Controller: v2.0 build 1

Let me try this solution : [Not working on my PC (maybe because of Wayland?)](https://github.com/LordAmit/Brightness/issues/107)

**Comment by Kogam22** [comment]
Works fine on xorg. Thanks you !

**Comment by LordAmit** [comment]
Glad to know.  :)
