### ISSUE TITLE
Set Focus to Primary Slider On Load

### ISSUE THREAD

**Issue by xSeekTruthx** [LordAmit/Brightness#126]
**Is your feature request related to a problem? Please describe.**
The problem is when Brightness Simple loads, nothing inside the box is set to focus. Meaning you need to manually click on the slider to start adjusting it. When using multiple monitors on Ubuntu, the controller does not always load on the monitor that you currently have turned on. As such, you have to either drag the controller to the viewing monitor, or turn on another monitor.

**Describe the solution you'd like**
Setting focus to the Primary slider On Load would allow the user to adjust all monitor settings using up and down, and tab keys to cycle through the monitors to adjust all brightness without needing to drag over and click inside the brightness simple program, or the need to turn on additional monitors.

**Describe alternatives you've considered**

**Additional context**
I've tried slider1.focus(), hbox1.focus(), primary_scroll.focus() and self.primary_scroll.focus() in various places inside the python code. Nothing seems to highlight the first horizontal scroll as soon as it loads without having to do a manual mouse click.

**Comment by LordAmit** [comment]
Quick questions:
- Which linux distro are you using? 
- Does the brightness controller window get focus but the slider does not? Or the window also stays out of focus?

**Comment by xSeekTruthx** [comment]
Upon loading the window gets Focus but the slider does not I actually have to click inside to focus on the slider. I am using Ubuntu 14.04
Seek Truth

**Comment by apandada1** [comment]
I am using Linux Mint 19.1 (latest version from the PPA) and it does focus on the primary brightness slider.

**Comment by LordAmit** [comment]
He already tried doing that based on his first post. 

Problem is, it is also being focused when I run it from the start in Ubuntu 18.04 LTS (I am using it right now).

It might have to do with how WxWidgets are being handled in Ubuntu 14.04 as well. 

Can you modify the code,  change it to this and see what happens?: 
```
self.InitUI()
self.Center()
self.Show()
self.Raise(True)
```

The change is only the last line, around line 84.

**Comment by xSeekTruthx** [comment]
Thank you for responding,

Added code in correct location, 8 spaces and self.Raise(True)
brightness-simple now doesn't load.
Removed the line, loads without issue.

Thank you

**Comment by LordAmit** [comment]
Hmm.
To be honest, I am at a loss here. It should work, and at least tab keys should be working. I wonder if that has something to do with WxWidgets and Ubuntu, instead of something at my end. Part of the issue is recreating - and I also can not recreate it.

I am still looking into it, but probably we need to be focusing on releasing v3 of Brightness Controller which will be created with better GUI toolkits with all the facilities of Controller 1 and 2. I will tag you here when we can look better into your issue at that time. 

Thank you again for your time and for letting us know about it.

**Comment by xSeekTruthx** [comment]
This is not an issue for me at present time and was likely specific to how my OS loads. Simple is also depreciated. Cheers!
