### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by MichelangeloConserva** [LordAmit/Brightness#129]
Your tool is awesome, I use it every day on my ubuntu laptop but I'd like to use it on windows 10 too.
I tried to use the scripts on a windows machine but obviously there are several problems.
Will you ever make a windows version? 
If someone thinks it is worth I can contribute.

**Comment by LordAmit** [comment]
Hi!

I am really glad to know that you are finding it useful. 

Making a Windows version? Depends on a few factors. 

Right now I do not know how it can be integrated with Windows. I will be really glad if you help me by finding a few information I require to do that:

- Is brightness controllable using CLI in Windows? If so, how?
- How to gain list of displays / number of connected displays using CLI, and most importantly,
- Are there any already existing tool in Windows that helps you to do everything already? (If there is, there is no need for me to make yet another controller!) 
 
Thank you again!

**Comment by MichelangeloConserva** [comment]
>  Is brightness controllable using CLI in Windows? If so, how? 

After some researches I found that these might be of some help

* [using prompt](https://superuser.com/questions/472081/can-i-force-a-greater-screen-brightness-from-windows-command-prompt)
* [using power shell](https://blogs.technet.microsoft.com/heyscriptingguy/2013/07/25/use-powershell-to-report-and-set-monitor-brightness/)

This should be the command to use in the power shell
```
(Get-WmiObject` -Namespace root/WMI -Class WmiMonitorBrightnessMethods).WmiSetBrightness(1,{percentage of brightness})
```
&nbsp;
>  How to gain list of displays / number of connected displays using CLI

There are a couple of WMI classes that provide information about resolution and monitors. One of these classes is the Win32_VideoController class. I can query this by using Get-CimInstance in Windows PowerShell 3.0, or I can use Get-WmiObject in Windows 7 with the default Windows PowerShell 2.0. [cit from](https://blogs.technet.microsoft.com/heyscriptingguy/2013/10/03/use-powershell-to-discover-multi-monitor-information/)
The command is: 
```
Get-WmiObject win32_videocontroller
```
&nbsp;
>  Are there any already existing tool in Windows that helps you to do everything already? (If there is, there is no need for me to make yet another controller!)

Yes there is one. It's called Monitorian but it doesn't work. I tried with different machines and obtained the same result.

**Comment by apandada1** [comment]
A google search shows that there are lots of brightness controlling softwares for Windows. https://www.raymond.cc/blog/software-to-adjust-monitor-brightness-and-contrast-for-dell-studio-one-desktop/

**Comment by MichelangeloConserva** [comment]
I'll check them again but the problem is that they don't work with more than one monitor

**Comment by MichelangeloConserva** [comment]
Most of the tools online described in the link you posted are not available anymore and the others do not work

**Comment by LordAmit** [comment]
Hi Michel,
Thanks for the resources. Right now I am overwhelmed by current obligations, but in the next iteration of Brightness Controller, I will definitely explore the sources you so kindly shared.

Thank you so much for your efforts!

**Comment by MrWoodle** [comment]
I have a brightness control app that I wrote for windows 10 (i am an amateur programmer) but it does the trick and I can even schedule the screens to dim and undim at certian times of the day. It is based on another open source app.  If you want to contact me I will send it to you.

**Comment by MichelangeloConserva** [comment]
I'd like to see your app but I don't know how to contact you.

**Comment by MrWoodle** [comment]
Can I post a link on here? maybe you can email me.  mrwoodle at gmail

**Comment by MichelangeloConserva** [comment]
Yes you can. This may help someone else with the same problem!

**Comment by LordAmit** [comment]
Hi! 
@MrWoodle I don't see any problem with sharing links here. I will really appreciate it if the link is to the repository by the way, instead of just the executable. :dancer:
