### ISSUE TITLE
Schedule the dimness

### ISSUE THREAD

**Issue by MrWoodle** [LordAmit/Brightness#131]
Would you be able to create a simple user interface to set a schedule for the dimness?  For example,  I want to have my end users be able to schedule dimness to happen everyday at dusk or at a particular time like 7:00 PM.

**Comment by apandada1** [comment]
Check this out.
https://askubuntu.com/a/378981/124466

The command to schedule should be something like `brightness-controller; sleep 10; kill all brightness-controller`

You need to save the required configuration in Brightness Controller beforehand.

**Comment by LordAmit** [comment]
I would instead create a mechanism that depends on existing schedulers available in Linux :) There are already a few GUI schedulers available, why make a new one :dancing_men:
