### ISSUE TITLE
breaking the shutdown process permanently

### ISSUE THREAD

**Issue by 3dformortals** [LordAmit/Brightness#132]
**Describe the bug**
kubuntu 18.04... break the shutdown (every boot).... at least last half year(few months)

**To Reproduce**
1. boot
2. `Ctrl + Alt + del`
3. choose `shutdown`
4. fail with error `Plasma Workspace
Logout canceled by '/usr/share/brightness-controller/init.py' `

**Expected behavior**
shutdown system

**Screenshots**
no need screen shot... shutdown system work after manually kill icon from tray(which too need twice call `quit` command) . I wait half year using `simple` version... few days ago i try updated `full version` and still no fixes. I go back to simple again. But before updates close half year ago `full version` work normal, before tray icon was added..

**Comment by LordAmit** [comment]
Hmm, I can reproduce the bug in KDE 18.04 myself.

@jahan-addison I think this issue is originating from closeEvent at init.py; probably due to event.ignore() when the app is minimized. Can you check this?

**Comment by 3dformortals** [comment]
> Can you check this?

when app not in tray , but on screen, the situation is similar... same error and behavior

**Comment by jahan-addison** [comment]
Thanks @3dformortals, I'll look into this.

**Comment by jahan-addison** [comment]
PR: https://github.com/LordAmit/Brightness/pull/133
