### ISSUE TITLE
Issues after Uninstall

### ISSUE THREAD

**Issue by flashysport101** [LordAmit/Brightness#136]
OS: Ubuntu
Distro: 
output of `xrandr -q`
Version of Brightness Controller: 1.2.8

I don't how the brightness controller changes my brightness, but every time I uninstall, the brightness changes to something I don't want it too and I have to reinstall just to undo the change. Help?

**Comment by LordAmit** [comment]
Hmm, that's fairly weird and unheard of. Brightness Controller should not be affecting the brightness once it is uninstalled.  

So, a few questions:
Say your default brightness level starts at 100. Note that, that's the hardware-based brightness.
Using the Brightness Controller you change the brightness to.. 80. Then you uninstall it.

After restarting -is it back to the previous 100? Or something completely different altogether?

**Comment by LordAmit** [comment]
Also, please provide the requested information in the default template, i.e. Ubuntu version (18, 19.. etc), The distro (lubuntu/ubuntu/kubuntu) and the output of `xrandr -q `.

**Comment by flashysport101** [comment]
OS: Ubuntu 18.04
Distro: Ubuntu
xrandr -q 
1920x1080     60.00*+  59.96    50.00    59.94    59.93  
   1680x1050     69.88    59.95    59.88  
   1600x1024     60.17  
   1400x1050     74.76    70.00    59.98  
   1600x900      59.95    59.82  
   1280x1024     75.02    60.02  
   1440x900      59.89    59.90  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      75.00    75.00    70.00    60.00  
   1280x720      60.00    59.99    59.86    60.00    50.00    59.94    59.74  
   1024x768      75.05    60.04    75.03    70.07    60.00  
   960x720       75.00    60.00  
   928x696       75.00    60.05  
   896x672       75.05    60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   832x624       74.55  
   960x540       59.96    59.99    59.63    59.82  
   800x600       75.00    70.00    65.00    60.00    72.19    75.00    60.32    56.25  
   840x525       74.96    69.88    60.01    59.88  
   864x486       59.92    59.57  
   720x576       50.00  
   800x512       60.17  
   700x525       74.76    70.06    59.98  
   800x450       59.95    59.82  
   720x480       60.00    59.94  
   640x512       75.02    60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    72.81    75.00    66.67    60.00    59.94  
   720x405       59.51    58.99  
   720x400       70.08  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       75.00    75.00    70.00    60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       75.03    70.07    60.00  
   512x288       60.00    59.92  
   416x312       74.66  
   480x270       59.63    59.82  
   400x300       72.19    75.12    60.32    56.34  
   432x243       59.92    59.57  
   320x240       72.81    75.00    60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
   Version of Brightness Controller: 1.2.8
   For me, the brightness 50 matches the (default) brightness before I installed the brightness controller. When I uninstall, it defaults to a 100 brightness.

**Comment by LordAmit** [comment]
That's probably your hardware brightness then. Generally, hardware brightness is saved with the display settings, and are stored across the startup/shutdown cycle. There is no code segment in the Brightness Controller, especially in version 1.2.8, that can affect the brightness after the uninstallation since it does this at the software level.

**Comment by flashysport101** [comment]
If so, how would be able to save my brightness as 50 using the brightness controller, as it defaults back to 100 after a restart?

**Comment by LordAmit** [comment]
Currently, it does not support that feature yet. 
However, we are working on the next release which should be supporting it :)

**Comment by flashysport101** [comment]
Ok thanks looking forward to it!
