### ISSUE TITLE
RBG control stopped working on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by TimTom68** [LordAmit/Brightness#139]
**Describe the bug**
RGB control used to work, but would sometimes reset to default (as in 100% RGB, not brightness controller default setting), to fix this i would just click on the app and slide the dial and it would go back to working.
Now, it only changes RGB while sliding the dials, but as soon as the dial isn't sliding, it reverts back to not working, as in 100% RGB even though dials aren't full.  So it only works when sliding, nothing that lasts

![Screenshot from 2019-07-03 10-40-02](https://user-images.githubusercontent.com/44717100/60600845-f26a3e80-9d7e-11e9-9b8e-ae4bcf289557.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Browser: Chrome & Firefox (i dont think this matters though)

**Additional context**
the output of `xrandr -q`:
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 340mm x 190mm
   1920x1080     60.00*+
   1680x1050     59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      60.00    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1368x768      60.00    59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.81    59.91  
   1152x864      60.00  
   1280x720      59.86    60.00    59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   640x360       59.84    59.32    60.00  
HDMI1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)

**Comment by LordAmit** [comment]
What's the icon between the brightness controller and wifi?

**Comment by TimTom68** [comment]
f.lux, which hasn't been working, but auto starts. I closed it and now brightness controller works! thanks!

**Comment by LordAmit** [comment]
thought so. glad to know it works :grin:
