### ISSUE TITLE
How to setup it on raspbian OS ?

### ISSUE THREAD

**Issue by rusikf** [LordAmit/Brightness#141]
Hi, after installing this on Raspberry PI 4( Raspbian OS based on Debian) with LG monitor through micro hdmi, I cannot adjust brightness. I installed this utility( manual installation), but it doesn't works

Do you have any ideas, what cause the problem?

Thanks

**Comment by LordAmit** [comment]
I'd first check is the display/brightness is supported by `xrandr`.  If it is not, then the brightness controller not working is expected, since it directly uses `xrandr` under the hood.

**Comment by rusikf** [comment]
@LordAmit thanks for response:)

No, it doesnt actually works( I described detaily here https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=250869)

Can you please advise another tool , which I can try to use?
Thanks!

**Comment by LordAmit** [comment]
something like this might be able to help:
https://github.com/linusg/rpi-backlight
But I do not know much about rasps, sorry :(
