### ISSUE TITLE
Reauthorize my commits

### ISSUE THREAD

**Issue by zdroid** [LordAmit/Brightness#142]
My old commits are not authorized properly due to an email change. [There](https://github.com/zdroid/dotfiles/blob/master/git/bin/author-rewrite)'s a script to fix it. Old email is legospace9876@gmail.com (deleted), new one is the one on my profile.

**Comment by LordAmit** [comment]
My old friend, welcome back. I missed you and kept wondering how you disappeared. 👯‍♂

**Comment by LordAmit** [comment]
Check back, I believe I have _rewritten history_. 😉

**Comment by zdroid** [comment]
Thanks. It's solved. :man_dancing:
