### ISSUE TITLE
Got shrunk unable to expand

### ISSUE THREAD

**Issue by bharish1997** [LordAmit/Brightness#145]
Application has been shrinked unable to expand.

**Screenshots**
![Screenshot from 2020-01-11 14-22-40](https://user-images.githubusercontent.com/46044484/72201835-18834080-347e-11ea-8f4d-88cf65e7c083.png)

**Desktop (please complete the following information):**
 - OS: UBUNTU
 - Browser: CHROME

**Comment by LordAmit** [comment]
Please provide the full information requested in the issue template :)
