### ISSUE TITLE
`python-pyside` is not available in 20.04 anymore

### ISSUE THREAD

**Issue by LordAmit** [LordAmit/Brightness#146]
`python-pyside` is not available in 20.04 anymore (installed in VM). I will try to add it to the ppa in the same way, but I am not sure whether it will work, as it has a huge number of dependencies.

However, `python3-pyside` is available in 20.04. So, it may be easier to port the code to python 3, instead of rewriting.

_Originally posted by @apandada1 in https://github.com/LordAmit/Brightness/issues/143#issuecomment-574587673_

**Comment by LordAmit** [comment]
Adding any more dependencies is not suggested. Porting to PySide2 will be easier, but we will probably have to leave behind some of the recent features as well.

The issue is with time; I can barely manage any time with my current constraints even though I want to. Do you want to start porting it to PySide2 minus the advanced features (such as minimizing to tray/singleton)?

**Comment by LordAmit** [comment]
@apandada1 - since it is a different issue from the original, I separated it. Please check the above response.

**Comment by apandada1** [comment]
Ok, I will try to port. I will keep you updated. And, #143 is now fixed. Also, the v1 still works in 20.04.

**Comment by apandada1** [comment]
Also, pyside is still available from pip https://pypi.org/project/PySide/. So, if we remove pyside from the dependency of the .deb, and ask users to install pyside manually from pip, that may be a temporary solution.

**Comment by LordAmit** [comment]
Thanks! See if you can generate .pys file from the .ui files using `pyside2-uic` first. That will make your job a lot easier.

**Comment by apandada1** [comment]
The above trick (installing pyside from pip, and removing `python-pyside` from list of dependencies works.

**Comment by apandada1** [comment]
I successfully generated all py files from the .ui files using `pyside2-uic`
When I run `init.py` from python2, I get 
```
Traceback (most recent call last):
  File "../init.py", line 662, in <module>
    WINDOW = MyApplication()
  File "../init.py", line 53, in __init__
    self.ui.setupUi(self)
  File "/home/archisman/brightness-test/brightness/debian/brightness-controller/usr/share/brightness-controller/ui/mainwindow.py", line 23, in setupUi
    MainWindow.setMinimumSize(QSize(701, 340))
TypeError: 'PySide.QtGui.QWidget.setMinimumSize' called with wrong argument types:
  PySide.QtGui.QWidget.setMinimumSize(PySide2.QtCore.QSize)
Supported signatures:
  PySide.QtGui.QWidget.setMinimumSize(PySide.QtCore.QSize)
  PySide.QtGui.QWidget.setMinimumSize(int, int)
```
When I run it from python3 I get 

```
 Traceback (most recent call last):
  File "../init.py", line 23, in <module>
    from util.QtSingleApplication import QtSingleApplication
  File "/home/archisman/brightness-test/brightness/debian/brightness-controller/usr/share/brightness-controller/util/QtSingleApplication.py", line 31, in <module>
    class QtSingleApplication(QApplication):
  File "/home/archisman/brightness-test/brightness/debian/brightness-controller/usr/share/brightness-controller/util/QtSingleApplication.py", line 32, in QtSingleApplication
    messageReceived = Signal(unicode)
NameError: name 'unicode' is not defined
```

**Comment by LordAmit** [comment]
That's actually great, and what I was hoping for! 😄 
You see, these errors mean that the ui files are compatible with pyside2, so we can use them as it is.

However, the init.py file was written using PySide2, which has a bit different syntax / architecture compared to PySide2. In addition, init.py is also probably written using Python2, instead of Python3. 

In both cases, we need to change the classes being called as PySide2 classes, instead of PySide.

For example, look at this:

```TypeError: 'PySide.QtGui.QWidget.setMinimumSize' called with wrong argument types:
  PySide.QtGui.QWidget.setMinimumSize(PySide2.QtCore.QSize)
Supported signatures:
  PySide.QtGui.QWidget.setMinimumSize(PySide.QtCore.QSize)
  PySide.QtGui.QWidget.setMinimumSize(int, int)```

The argument type, i.e. what we are providing as the argument is correct. We are supposed to provide the PySide2.QtCore.QSize. 

But the place where we are calling it from was written for PySide, so it is expecting PySide type QSize.

I hope it makes sense?

**Comment by apandada1** [comment]
I am now using Pyside2, and edited some lines to make it compatible (had to import QtWidgets and use it, and so on). I also changed the syntax to python3 in multiple files.
But, now I get a new error (which is now shown in Python3 and was shown in Python2 as well before adopting Python3 syntax).

```
Traceback (most recent call last):
  File "init.py", line 665, in <module>
    WINDOW = MyApplication()
  File "init.py", line 55, in __init__
    self.ui.setupUi(self)
  File "/home/archisman/brightness-test/brightness/debian/brightness-controller/usr/share/brightness-controller/ui/mainwindow.py", line 220, in setupUi
    self.comboBox.addItem(QString())
NameError: name 'QString' is not defined
Segmentation fault
```
I tried defining QString(x) as suggested by https://gis.stackexchange.com/questions/313949/name-qstring-is-not-defined, but it did not work. I am uploading the code to apandada1/Brightness/v3

**Comment by apandada1** [comment]
I have tried to correct most of the errors. Right now the program runs with Pyside 2 and Python 3, however, it cannot correctly read output from `xrandr -q` in https://github.com/apandada1/Brightness/blob/v3/src/util/check_displays.py due to some difference between Python 2 and 3, related to https://stackoverflow.com/questions/33054527/typeerror-a-bytes-like-object-is-required-not-str-when-writing-to-a-file-in.
Please check my branch (v3), and if you know how to fix that, let me know.

**Comment by apandada1** [comment]
The program can now control brightness and color temps. It could not read output because **it cannot save the input** correctly (it can correctly read output). When I try to save to an output file (or save settings to default), I get 
```
Traceback (most recent call last):
  File "./init.py", line 484, in save_settings
    file_path
  File "/home/archisman/Documents/GitHub/Brightness/src/util/write_config.py", line 46, in write_primary_display
    config.write(configfile)
  File "/usr/lib/python3.6/configparser.py", line 919, in write
    self._sections[section].items(), d)
  File "/usr/lib/python3.6/configparser.py", line 923, in _write_section
    fp.write("[{}]\n".format(section_name))
TypeError: a bytes-like object is required, not 'str'
```
Any suggestions? I did not understand this byte/str issue.

**Comment by LordAmit** [comment]
Never mind what I said earlier in email, check this
https://docs.python.org/3/library/configparser.html

Instead of
 
```python
config.set('primary', 'brightness', 99)
```

Change them to like this:

```pythonconfig['primary]['brightness'] = 99
```

WIth sections being introduced like this:

```python
config['primary'] = {}
```

Then, do a print on config before writing it in a file to see what's going on. 

Also, the file is being opened in binary mode (wb); we gotta change it to overwrite.

**Comment by apandada1** [comment]
If I use the code 
```
    config = configparser.RawConfigParser()
    config['type'] = {}
    config['primary'] = {}
    config['primary']['has_secondary'] = "False"
    if p_br_rgb is None:
        config['primary']['brightness'] = 99
        config['primary']['red'] = 99
        config['primary']['green'] = 99
        config['primary']['blue'] = 99
        config['primary']['temperature'] = 99
    else:
        config['primary']['brightness'] = p_br_rgb[0]
        config['primary']['red'] = p_br_rgb[1]
        config['primary']['green'] = p_br_rgb[2]
        config['primary']['blue'] = p_br_rgb[3]
        config['primary']['temperature'] = p_br_rgb[4]

    with open(file_path, 'wb') as configfile:
        config.write(configfile)
```
I get an error
```
Traceback (most recent call last):
  File "./init.py", line 484, in save_settings
    file_path
  File "/home/archisman/Documents/GitHub/Brightness/src/util/write_config.py", line 40, in write_primary_display
    config['primary']['brightness'] = p_br_rgb[0]
  File "/usr/lib/python3.6/configparser.py", line 1237, in __setitem__
    self._parser._validate_value_types(option=key, value=value)
  File "/usr/lib/python3.6/configparser.py", line 1177, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```
To get strings, if I change to `str(p_br_rgb[0])`, I get the previous error 
```
Traceback (most recent call last):
  File "./init.py", line 484, in save_settings
    file_path
  File "/home/archisman/Documents/GitHub/Brightness/src/util/write_config.py", line 47, in write_primary_display
    config.write(configfile)
  File "/usr/lib/python3.6/configparser.py", line 919, in write
    self._sections[section].items(), d)
  File "/usr/lib/python3.6/configparser.py", line 923, in _write_section
    fp.write("[{}]\n".format(section_name))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by apandada1** [comment]
Got it!  ` with open(file_path, 'w+') as configfile:` does the job by overwriting.
