### ISSUE TITLE
unmet dependencies:  brightness-controller : Depends: python but it is not installable

### ISSUE THREAD

**Issue by wonderingabout** [LordAmit/Brightness#154]
**Describe the bug**
i can't install brightness-controller on ubuntu 20.04 (ppa install)

**To Reproduce**
not sure how to reproduce it, i sucessfully installed it at last week and it worked as intended for many days.
Not sure when it broke, but might be after i installed `nvidia-cuda-toolkit`

**Screenshots**
![python is not installable](https://user-images.githubusercontent.com/38690718/73334620-7e890980-426d-11ea-9f2f-e8b13a330c61.png)

![python install 2](https://user-images.githubusercontent.com/38690718/73334625-80eb6380-426d-11ea-801a-6469e26af5d5.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04

**Additional context**
Add any other context about the problem here. Typically, the output of `xrandr -q`.

this is a fresh install of ubuntu 20.04, less than 1 week of use.

**Comment by apandada1** [comment]
Probably python got replaced by python2 recently

**Comment by apandada1** [comment]
Can you check what it says when you do `sudo apt install python3-pyside2.qtcore`?

**Comment by wonderingabout** [comment]
after install, problem persists

![pyside](https://user-images.githubusercontent.com/38690718/73335186-edb32d80-426e-11ea-9d7e-566dd86e9886.png)

**Comment by apandada1** [comment]
Ok, I will change dependency from `python` to `python2`.

**Comment by wonderingabout** [comment]
thanks for your reactivity, i'm open to test until we hopefully fix this

**Comment by wonderingabout** [comment]
it seems python2 will be dropped as well in ubuntu 20.04 :
https://www.phoronix.com/scan.php?page=news_item&px=Python-2-EOL-Ubuntu-20.04

**Comment by apandada1** [comment]
We have ported the main program to python3, only the file `brightness-reset` depends on Python 2.
I have initiated the building process in Launchpad. Run apt-get update **after one hour** and see if the new version (2.3.2) can be installed.

If you are able to, you are more than welcome to port this file to python3. https://github.com/LordAmit/Brightness/blob/releases/usr/bin/brightness-reset

**Comment by wonderingabout** [comment]
i'd like to, but my python knowledge is basic
in one hour i'll be out, but when i come back i'll keep you updated

reactivity is greatly appreciated :+1:

**Comment by LordAmit** [comment]
@apandada1 , Try this

**Comment by wonderingabout** [comment]
great news, issue solved :+1: 

![solved](https://user-images.githubusercontent.com/38690718/73340495-1d683280-427b-11ea-949a-9ca4b3045b3c.png)


thanks for your reactivity once again :+1:

**Comment by LordAmit** [comment]
Cool! Thanks for being so responsive, @apandada1 
@wonderingabout  - glad to know that it works for you now. If possible, tell your friends about it. (if not, totally understandable)
🕺

**Comment by apandada1** [comment]
> @apandada1 , Try this
> https://docs.python.org/2/library/2to3.html

For some reason, 2to3 could not do it (I used 2to3 in all other files), and I was unable to do it manually. Can you do it? I will remove python2 from the list of dependencies once this is done.

**Comment by LordAmit** [comment]
Yeah, going through the changes you made in v3 and making some changes here and there. After that I will take a look at the reset one.

**Comment by apandada1** [comment]
@wonderingabout You can use the qt5ct tool to make brightness-controller and all other qt apps use the native theme in gnome

**Comment by wonderingabout** [comment]
@apandada1 
oh i interesting
i knew about gnome-tweak-tool, will try this one too :+1:
