### ISSUE TITLE
Brightness Controller - Porting to PySide2 - Alpha

### ISSUE THREAD

**Issue by LordAmit** [LordAmit/Brightness#156]
Hello,

@apandada1 made things a lot easier for me by porting a major portion of the code in Python3 as well as rewriting calls to PySide2 modules.
 
For the remaining part, I "think" I have completed the porting by making proper calls to PySide2 and Python3. Moreover, I also made several changes. Some of these are:

- brightness-reset now relies on utility
- brightness-controller.svg was moved under ui, and is referenced in the code base as such. @apandada1 - you might have to change the build script for PPA slightly to handle that. Let me know if I can make this easier for you somehow. The SVG is referenced in two specific places in the code base as far as I remember.
- The minimize to tray part was also modified. Now it will check if it is possible to be minimized to tray. If possible, closing minimizes it to tray and quitting from tray asks for confirmation. If not possible, the user is asked for confirmation directly. 

What you all need to do:

- Checkout v3 branch
- Test things
- Lemme know if things are running as supposed to.
tags: 
@apandada1
@jahan-addison 
@zdroid 

BTW, @apandada1  also mentioned to me that Brightness Controller's latest version was downloaded more than 100000 times just from PPA. Which.is.a.LOT!

:tada: :dancing_women: :dancer: :dancing_men:

**Comment by apandada1** [comment]
It is best to keep icon inside use/share/icons.

**Comment by LordAmit** [comment]
Hmm.
I am looking into it; as well as looking into setup tools.

**Comment by LordAmit** [comment]
BTW, @apandada1 - do you think Debian package making will be better with setuptools? 

I am talking about things like this
https://setuptools.readthedocs.io/en/latest/setuptools.html

**Comment by apandada1** [comment]
Can we make a debian package with setuptools? It is better to use native version of PySide2 instead of the one from pip because the native version correctly follows system themes etc.

**Comment by apandada1** [comment]
These might work. https://stackoverflow.com/questions/7110604/is-there-a-standard-way-to-create-debian-packages-for-distributing-python-progra

**Comment by apandada1** [comment]
1. Replace is by ==
2. It does not quit in Manjaro, and this is the output when I try to quit.
`./init.py:42: SyntaxWarning: "is" with a literal. Did you mean "=="? 
 if self.no_of_displays is 1: 
./init.py:45: SyntaxWarning: "is" with a literal. Did you mean "=="? 
 elif self.no_of_displays is 2: 
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 759, resource id: 54526030, majo
r code: 40 (TranslateCoords), minor code: 0 `

And, for some reason, print(reply) gives `16384`.

**Comment by LordAmit** [comment]
What about type(reply)?

**Comment by LordAmit** [comment]
> Can we make a debian package with setuptools? It is better to use native version of PySide2 instead of the one from pip because the native version correctly follows system themes etc.

Not sure, if I remember correctly - setuptools make it easier for making Debian packages. What do you mean by Native PySide2? From apt-get?

**Comment by apandada1** [comment]
Yes, from apt-get

On Thu, Jan 30, 2020, 9:58 AM Amit Seal Ami <notifications@github.com<mailto:notifications@github.com>> wrote:

Can we make a debian package with setuptools? It is better to use native version of PySide2 instead of the one from pip because the native version correctly follows system themes etc.

Not sure, if I remember correctly - setuptools make it easier for making Debian packages. What do you mean by Native PySide2? From apt-get?

**Comment by apandada1** [comment]
type(reply) is `<class 'int'>`

**Comment by apandada1** [comment]
Note that the reply is same in KDE Neon also. 16384 for yes and 65536 for no. And <class 'int'>

**Comment by LordAmit** [comment]
I was digging into it; looks like YES and NO are represented as those integer values in QT.

I made some changes; please let me know if it works or still throws warning related to YES and NO.

Also, let me know exactly which line and which method the warning is coming from as well.

**Comment by apandada1** [comment]
Bug1: **Now it cannot detect that only one display is connected, and cannot change brightness.**
It says 
`warning: output None not found; ignoring
xrandr: Need crtc to set gamma on.
Traceback (most recent call last):
  File "./init.py", line 261, in change_value_pbr
    Executor.execute_command(cmd_value)
  File "/home/archisman/Brightness/src/util/executor.py", line 23, in execute_command
    subprocess.check_output(string_cmd, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'xrandr        --output None         --brightness 0.9900000000000007        --gamma 1.0000000000000007:1.0000000000000007:1.0000000000000007' returned non-zero exit status 1.
`
Bug2: It still does not close in Manjaro.

**Comment by LordAmit** [comment]
Gotcha, fixed it. Had an issue with how I was finding the displays.

Also, introduced 
```
    sys.exit(APP.exec_())

```

With 

```
event.accept()
```

**Comment by LordAmit** [comment]
@apandada1 is it possible to upload a single file in Debian? I was thinking about freezing; so that it includes all dependencies and everything else in itself so that the user can run it without relying on external dependencies.

**Comment by apandada1** [comment]
No, but that is the idea behind snap packages (which might make a software with a few lines of code consume 100s of MB, as dependencies are not shared). But those are relatively slow in not so fast computers. Let's go for Debian packaging with setuptools.

**Comment by LordAmit** [comment]
Sigh. 

Alright, I guess for now I will make a script that makes it easier for you to make the package. I could not find any proper tutorial that covers everything I was looking for / covers things that'd help us do things we want to do. So I will include a file under utility that will work as a switch for Debian.
Based on the switch, it will change where it is looking for icon files.

**Comment by apandada1** [comment]
Right now packaging is really easy. I have made the layout, and I simply upload the necessary changes to apandada1/releases. Launchpad automatically copies the source and builds it

**Comment by LordAmit** [comment]
Yeah, but not everyone uses PPA - and whoever does not use PPA; brightness-controller will look for its icon under /usr/share/icon - which it will not find leading to confusion.

**Comment by LordAmit** [comment]
I think I got it. Will be committing soon!

**Comment by LordAmit** [comment]
@apandada1 Please check now.

Also, make sure you upgrade pyside2-uic since it fixes a major bug from earlier versions; the previous py files were breaking because of that bug as well I think. 

I will take a look at the window closing part if it is still not working for you.

**Comment by apandada1** [comment]
Both window closing and detecting display bugs are fixed.
Now there's setup.py, is setuptools already implemented?

**Comment by apandada1** [comment]
I will take this up. This page shows how to Debianize using setuptools https://stackoverflow.com/questions/17401381/debianzing-a-python-program-to-get-a-deb

**Comment by LordAmit** [comment]
> Both window closing and detecting display bugs are fixed.
> Now there's setup.py, is setuptools already implemented?
> 
> Also, we can now probably delete the icon file from the ui directory.

The setup.py is for cx_freeze; thought it might be useful if we want to release standalones; but the size is huge 😋 

About icon, yup. We can delete it. Let me know if you need help. And try making a build script that copies specific files from the src and puts it in a folder; like Debian maybe. If that works, we can stop including unnecessary files like *.ui and more. 🕺

**Comment by apandada1** [comment]
That script is already there. https://github.com/apandada1/Brightness/blob/releases/debian/install I can modify it to exclude ui files. I will see how to make debian source and binary packages with setup.py

**Comment by LordAmit** [comment]
> That script is already there. https://github.com/apandada1/Brightness/blob/releases/debian/install I can modify it to exclude ui files. I will see how to make debian source and binary packages with setup.py

Alrighty, let me know if things are working properly. I believe with the latest changes, we can now replace the master branch.

**Comment by apandada1** [comment]
Things are working properly. I will need some time to implement Debian packaging with setuptools as it is completely new to me.

**Comment by LordAmit** [comment]
Alrighty, branch v3 is now put as master, whereas the original master is now v2 branch. Also, the old v3 branch is removed from the origin. 

With that, I will take a bow and rest. 🕺

**Comment by LordAmit** [comment]
How are things at your end @apandada1 ?

**Comment by apandada1** [comment]
v2.3 is in the ppa (for 19.10 and 20.04), but I have not implemented setuptools yet. My midterms will end next week, I will see after that.

**Comment by LordAmit** [comment]
Ah, I thought it'd take time to get 2.3 in PPA - but you already did it. Thanks for that. 
For setuptools, take your time. No worries :D
