### ISSUE TITLE
Not working. Buttons greyed out.

### ISSUE THREAD

**Issue by 7--** [LordAmit/Brightness#157]
**Describe the bug**
Unable to make any adjustments

**To Reproduce**
`$ brightness-controller
`

**Expected behavior**
Able to adjust screen brightness. 

**Screenshots**
![Screenshot from 2020-02-12 00-54-05](https://user-images.githubusercontent.com/4725003/74306998-36b8b680-4d32-11ea-9dbf-1e31caa0a886.png)
![Screenshot from 2020-02-12 13-46-26](https://user-images.githubusercontent.com/4725003/74366504-23dbcb80-4d9e-11ea-9c22-46c461b7d541.png)

**Desktop (please complete the following information):**
Tried on Ubuntu 18 and 19
![Screenshot from 2020-02-12 13-47-29](https://user-images.githubusercontent.com/4725003/74366563-3f46d680-4d9e-11ea-866a-f03e59aed76f.png)

**Additional context**
Reinstalled my video driver then this happened. No other dimmers work. 

> $ xrandr -q
> Screen 0: minimum 16 x 16, current 1920 x 1080, maximum 32767 x 32767
> XWAYLAND0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 510mm x 290mm
>    1920x1080     59.96*+

**Comment by LordAmit** [comment]
Hi,

please respond following the template instructions. Otherwise, we really can not determine what's going on.

**Comment by 7--** [comment]
What info. Template didnt ask for much

**Comment by apandada1** [comment]
@7-- Please provide the output of the command `xrandr -q`.

**Comment by 7--** [comment]
@apandada1  @LordAmit 
$ xrandr -q
Screen 0: minimum 16 x 16, current 1920 x 1080, maximum 32767 x 32767
XWAYLAND0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 510mm x 290mm
   1920x1080     59.96*+

**Comment by LordAmit** [comment]
Hi,

Looks like your system is using wayland session. Wayland is great, but unfortunately it does not allow us to change brightness in session. As far as I know, wayland will also stop being the default session in coming Ubuntu 20.04 LTS, since it is still not mature enough. 

Please change your desktop session to X.org.

**Comment by 7--** [comment]
@LordAmit That was it. Thanks a ton. I didn't know it was still in wayland mode.

**Comment by LordAmit** [comment]
Glad to know it worked out for you. Enjoy using it. 😄
