### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by ansidev** [LordAmit/Brightness#158]
**Describe the bug**
Broken UI on opening the application.

**To Reproduce**
1. Open the application.

**Expected behavior**
Perfect UI

**Screenshots**
https://imgur.com/a/kh2Fm7H

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
- Version 1.2.8

**Additional context**
xrandr -q: https://pastebin.com/ZvN0s8KN

**Comment by LordAmit** [comment]
Hi,

The simple version (1.x.x) is only provided for legacy reasons. We recommend you to use version 2.x.x.
