### ISSUE TITLE
Brightness Controller 2 does not working properly

### ISSUE THREAD

**Issue by ansidev** [LordAmit/Brightness#159]
**Video**
https://youtu.be/7MQ6atNnlsg

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10

**Comment by ansidev** [comment]
Note: V1 is working. but V2 is not working

**Comment by apandada1** [comment]
Since the brightness changes do not appear in a screen recording, I presume v2 is not changing brightness but v1 does. 
1. Please post the output of `xrandr -q`. 
2. And, can you run `brightness-controller` from terminal and post the output (if any) when you change the brightness value with the slider? If it does not work, python might show some error.

**Comment by ansidev** [comment]
https://pastebin.com/ZvN0s8KN

**Comment by apandada1** [comment]
Also, are you using v2 from the ppa?

**Comment by ansidev** [comment]
Yes

**Comment by apandada1** [comment]
How many displays are connected? Two? The output shows `HDMI-0 connected` (primary) and `eDP-1-1 connected`.

**Comment by ansidev** [comment]
At this time, only one. I 've updated output of `xrandr -q`

**Comment by ansidev** [comment]
> Since the brightness changes do not appear in a screen recording, I presume v2 is not changing brightness but v1 does.
> 
> 1. Please post the output of `xrandr -q`.
> 2. And, can you run `brightness-controller` from terminal and post the output (if any) when you change the brightness value with the slider? If it does not work, python might show some error.

https://pastebin.com/6DzAMHtK

**Comment by apandada1** [comment]
Check whether these three commands actually change the brightness `xrandr        --output HDMI-0         --brightness 0.8200000000000005        --gamma 1.0000000000000007:1.0000000000000007:1.0000000000000007`,
`xrandr        --output HDMI-0         --brightness 0.82        --gamma 1.0:1.0:1.0`, and `xrandr        --output HDMI-0         --brightness 0.8200000000000005`

**Comment by ansidev** [comment]
Same log: `xrandr: Need crtc to set gamma on.`

**Comment by apandada1** [comment]
Does it change the brightness? What about the last command without gamma?

**Comment by ansidev** [comment]
Nothing work, same logs for 3 commands.

At this time, only one primary monitor.

**Comment by apandada1** [comment]
And the v1 still works? Please check the output of these two.
`xrandr --output eDP-1-1 --brightness 0.62`
`xrandr --output eDP-1-1 --brightness 0.62 --gamma 1.0:1.0:1.0`

**Comment by ansidev** [comment]
Worked commands:

```
xrandr --output eDP-1-1 --brightness 0.8200000000000005
```

```
xrandr --output eDP-1-1 --brightness 0.5
```

**Comment by apandada1** [comment]
I think this is because the version in the PPA still does not have some of the very latest commits by LordAmit. @ansidev Could you download the latest code https://github.com/LordAmit/Brightness/archive/master.zip and run `python3 Brightness/src/init.py`, and check if it works? Then I will put this to PPA by tomorrow.

**Comment by ansidev** [comment]
It works, but the terminal log is showing:
```
qt.svg: Cannot open file '/path/to/Brightness/icons/brightness-controller.svg', because: No such file or directory
```

**Comment by apandada1** [comment]
That's fine. This probably is because it is not the installed version. I will upload it to the ppa tomorrow, and let you know.

**Comment by apandada1** [comment]
I have uploaded the latest code to ppa, and Launchpad will automatically build and host it within half an hour. @ansidev Please run `sudo apt update` and let us know whether it works.

**Comment by ansidev** [comment]
Worked, great!

**Comment by apandada1** [comment]
@ansidev From the youtube video it looks like you are using a GTK based DE, and Qt apps like v2 are not correctly following the system theme. You can use `qt5ct` (`sudo apt-get install qt5ct`, and run it from terminal/menu) to make v2 follow your system theme.

**Comment by apandada1** [comment]
This issue can be closed.
