### ISSUE TITLE
Wrong settings file generated by "Save current as default" (version 2.3.3)

### ISSUE THREAD

**Issue by epagone** [LordAmit/Brightness#163]
OS: GNU/Linux
Distro: Ubuntu 20.04 Focal Fossa
output of `xrandr -q`
```
Screen 0: minimum 8 x 8, current 3600 x 1080, maximum 8192 x 8192
DVI-I-0 disconnected (normal left inverted right x axis y axis)
VGA-0 connected 1680x1050+1920+0 (normal left inverted right x axis y axis) 433mm x 271mm
   1680x1050     59.95*+
   1600x1200     60.00  
   1440x900      74.98    59.89  
   1400x1050     59.98  
   1360x765      60.00  
   1280x1024     75.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
DVI-I-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1440x900      74.98    59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    60.32    56.25  
   640x480       75.00    72.81    59.94  
HDMI-0 disconnected (normal left inverted right x axis y axis)
```
Version of Brightness Controller: `2.3.3-0~202003280630~ubuntu20.04.1`

Error message:
```bash
$ brightness-controller
Traceback (most recent call last):
  File "/usr/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.8/collections/__init__.py", line 891, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 883, in __missing__
    raise KeyError(key)
KeyError: 'source'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/brightness-controller/init.py", line 702, in <module>
    WINDOW = MyApplication()
  File "/usr/share/brightness-controller/init.py", line 88, in __init__
    self.load_settings(self.default_config)
  File "/usr/share/brightness-controller/init.py", line 571, in load_settings
    loaded_settings = ReadConfig.read_configuration(file_path)
  File "/usr/share/brightness-controller/util/read_config.py", line 40, in read_configuration
    p_source = config.get('primary', 'source')
  File "/usr/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'source' in section: 'primary'

$ python3 --version
Python 3.8.2
```

**Comment by LordAmit** [comment]
Hmm,
Can you please show the contents in the settings file?
it is under 
```
~/.config/brightness_controller/settings
```

**Comment by epagone** [comment]
Thanks for looking into the problem.

```
$ cat ~/.config/brightness_controller/settings 
[type]

[primary]
has_secondary = True
brightness = 79
red = 99
green = 99
blue = 99
temperature = DVI-I-1

[secondary]
brightness = 79
red = 99
green = 99
blue = 99
temperature = VGA-1
```

**Comment by epagone** [comment]
Update: I've hunted down the real issue. It is the `Save current as default` command that saves the `settings` file in the wrong format (i.e. without the `source =` line).

<sub>For the records, what happened is that after I installed Ubuntu 20.04, I have run for the first time `brightness-controller` adjusting the settings to suit my system and saved them as default. Then I added it to the start-up apps list and forgot about it for several days (while I was busy setting up the new installation) without realising that it was not starting at each reboot. Finally, I noticed it was not running without remembering that it actually started the very first time and executed it from the terminal and here we are at the beginning of this issue</sub>

**Comment by apandada1** [comment]
This error was there even before the rewrite to python3. This is the my `settings` file (from v2.2 in Python 2). Somehow, v2.3 worked despite this bug in early builds of 20.04 and earlier versions of Ubuntu.
```
[type]

[primary]
has_secondary = False
brightness = 99
red = 99
green = 99
blue = 99
temperature = eDP-1
```

**Comment by LordAmit** [comment]
@epagone - thank you for going above and beyond in your investigation. That helped us immensely.

I made some changes which should fix it. If you want to try it out, you can change it by replacing the write_config.py and read_config.py, as well as init.py files from this repository. However, if you do not want to experiment on it, please wait for us to release the changes through PPA.

@apandada1 can you pull the changes and see if things work?

**Comment by apandada1** [comment]
I don't have 20.04, but this seems to work well in a VM in 20.04. Shall I push it to the ppa?

**Comment by apandada1** [comment]
I don't have 20.04, but this seems to work well in a VM in 19.10. Shall I push it to the ppa?

**Comment by LordAmit** [comment]
It should not differ across OSes. I made some more changes, please take a look at them as well.

**Comment by apandada1** [comment]
I have requested a build in Launchpad (only for 20.04), and it will be built in an hour. @epagone Please run `sudo apt update` after and hour and so, and let us know whether it works.

**Comment by epagone** [comment]
Thanks for the quick response. Unfortunately, the new package fails to install.
```
Setting up brightness-controller (2.3.4-0~202004250741~ubuntu20.04.1) ...
  File "/usr/share/brightness-controller/util/write_config.py", line 21
    def _default_config(config, display_type: str = 'primary'):
                                            ^
SyntaxError: invalid syntax

dpkg: error processing package brightness-controller (--configure):
 installed brightness-controller package post-installation script subprocess returned error exit status 101
```

```bash
$ python3 --version
Python 3.8.2
```

**Comment by apandada1** [comment]
I get this error when I try to install the deb file in 19.10. The strange thing is the program installed (despite showing error during installation) and runs correctly. And, it does not show this error when it is run, either from the installed .deb file or directly from the source.

@LordAmit Any idea about the invalid syntax thing?

**Comment by epagone** [comment]
@apandada1 wow, you're right! If I run version 2.3.4 there is no error and the program seems to work fine. Still, the installer throws an error (the one in my previous message) and says that the installation failed.

**Comment by apandada1** [comment]
Lintian does not show any error. I did not even know that dpkg checks Python syntax while installing. 

Looks like the `:` causes some error in the line `def _default_config(config, display_type: str = 'primary'):`

I got the same error.

**Comment by LordAmit** [comment]
Same error here. As for why, I got a few ideas, but solving it will require some experimentation.

@apandada1 do we have a alpha PPA channel? I want to test some changes for PPA without pushing them to the release channel :stuck_out_tongue_closed_eyes:

**Comment by apandada1** [comment]
I can make an alpha channel. Can you make a new branch (duplicate it from releases branch and name it patch) and make your changes in `usr/share` directory.

**Comment by apandada1** [comment]
The other option is, you make multiple versions of possible changes in different subdirectories of the new branch, and I will upload each of them to the alpha channel under different names so we can test all of them. Both options will take some time due to the difference in time zone.

**Comment by apandada1** [comment]
I have made the ppa. Let me know when you are done, and I will connect the dots. https://code.launchpad.net/~apandada1/+archive/ubuntu/brightness-alpha

**Comment by LordAmit** [comment]
> @LordAmit I can make an alpha channel. Can you make a new branch (duplicate it from releases branch and name it alpha) and make your changes in `usr/share` directory of the new branch. Meanwhile, I will make the ppa
@apandada1 
Hmm, but the releases under my branch are not reflecting the latest changes. I believe a pull request from your releases is necessary in my releases branch.

**Comment by epagone** [comment]
I have found an update today and it went smoothly, thank you! Now let's see if the programs works ok.

**Comment by LordAmit** [comment]
> I have found an update today and it went smoothly, thank you! Now let's see if the programs works ok.

please let us know 😄

**Comment by epagone** [comment]
It works, many thanks! The only issue that I now have is that its icon does not appear any more on the top bar, as it was happening previously. But this is a different issue, so I'll close this one.

**Comment by LordAmit** [comment]
Yeah, we disabled the system tray feature for now. It is a buggy feature that will be readded in the future, when we are sure that it is not buggy anymore.

**Comment by epagone** [comment]
> Yeah, we disabled the system tray feature for now. It is a buggy feature that will be readded in the future, when we are sure that it is not buggy anymore.

Ok. For what is worth, I found it very useful
