### ISSUE TITLE
Brightness Controller 2.3.4 -> Disabling System Tray Icon and Fixing Settings Saving

### ISSUE THREAD

**Issue by LordAmit** [LordAmit/Brightness#164]
The 2.3.4 includes several changes.

- Minimize to System Tray is disabled
- Fixed an issue in Settings save modules 

Minimize to System Tray as it stands, is weird. Even though the code superficially looks okay along with its control flow and conditions - it does not work. Which means either we are doing something wrong, or there is something wrong with how the UI signals are being received and processed. For example, declining to quit the app successfully calls `event.ignore()` which should prevent the app from shutting down. But the app shuts down anyway. :fearful: 

We have also received reports regarding it, such as #161, #160. 

Therefore, I decided to <strike>nuke :bomb: </strike> remove the minimize to system tray feature/close to tray feature altogether for now. It will be reintroduced when we know we implemented it in a way that works flawlessly. 

:man_dancing:

**Comment by LordAmit** [comment]
attn: @apandada1

**Comment by LordAmit** [comment]
Also, we gotta keep the version numbers consistent across everywhere. 
I just noticed that we are at 2.3.3 in PPA (maybe?), but it says 2.3 everywhere in the repo. 
Let me know when you want to bump the versions in PPA, I will update here and then you can use that version number in PPA :D

**Comment by apandada1** [comment]
Let's use 2.3.4. I tested it in a VM in Ubuntu 19.10. It saves settings correctly.

**Comment by LordAmit** [comment]
I removed all the tray related code. Does it work as intended?

**Comment by apandada1** [comment]
Yes

**Comment by apandada1** [comment]
It is in the PPA

**Comment by LordAmit** [comment]
thanks!
