### ISSUE TITLE
Can't install PPA on Ubuntu 20.04

### ISSUE THREAD

**Issue by denisrosset** [LordAmit/Brightness#165]
**Describe the bug**
A clear and concise description of what the bug is. If the contents of the subsections do not apply, simply replace the contents with N/A.

**To Reproduce**
1. On Ubuntu 20.04, run `apt-get install brightness-controller`

**Expected behavior**
Package installs.

**Screenshots**
Here is the relevant part of the installation log:
```
Setting up brightness-controller (2.3.4-0~202004250741~ubuntu20.04.1) ...
  File "/usr/share/brightness-controller/util/write_config.py", line 21
    def _default_config(config, display_type: str = 'primary'):
                                            ^
SyntaxError: invalid syntax

dpkg: error processing package brightness-controller (--configure):
 installed brightness-controller package post-installation script subprocess returned error exit status 101
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by denisrosset** [comment]
On the other hand, cloning the repository and running it manually works (with `python3 src/init.py`).

**Comment by LordAmit** [comment]
Hi,
Thank you for reporting it. We are aware and currently working on it to fix it.

**Comment by apandada1** [comment]
@denisrosset New version is up. Run `sudo apt update` and let us know whether it works.

**Comment by denisrosset** [comment]
I had uninstalled it. I did `apt-get install brightness-controller` and it's working again! thanks
