### ISSUE TITLE
Loading on startup

### ISSUE THREAD

**Issue by MilanCugur** [LordAmit/Brightness#173]
Whether automatic profile loading is possible at the system startup? 

Right now I have to re-adjust the lighting every time I turn up my computer.

Thanks in advance.

**Comment by apandada1** [comment]
Adjust the sliders to suit your eyes and click `File -> Save current as default`. Then, when you run Brightness Controller (you can add it to [startup applications](https://github.com/LordAmit/Brightness/issues/171)), it will load your previous settings.
