### ISSUE TITLE
coding confusion 

### ISSUE THREAD

**Issue by miabelleopal** [LordAmit/Brightness#174]
im trying to install the brightness controller through code and im not sure what im supposed to do next...

i coded: sudo add-apt-repository ppa:apandada1/brightness-controller
i pressed enter
but all i got was: [sudo] password for user:

what should i do?

**Comment by apandada1** [comment]
The command prompt is asking for your password. Enter your password and press enter (the password won't show up so that the person behind you cannot see it).
Then run the command `sudo apt update`, followed by `sudo apt install brightness-controller`

**Comment by apandada1** [comment]
This happens when installation of some software was interrupted. 
1. Restart your computer (if you already haven't).
2. Run`sudo apt install brightness-controller` again.

**Comment by miabelleopal** [comment]
i already tried this, nothing seems to be working :/
