### ISSUE TITLE
Brightness Level Not Changing

### ISSUE THREAD

**Issue by FedeCuci** [LordAmit/Brightness#179]
I am running Ubuntu 20.04 on wayland and the application just isn't working. I want to provide more specific info but I wouldn't know how. Could you tell me some useful info that you could need to debug this problem and how to get it? I would be happy to provide it!

As of now, the only thing I have tried is running the program as root from the terminal, but still to no success.

**Comment by apandada1** [comment]
Duplicate of https://github.com/LordAmit/Brightness/issues/177. Brightness Controller user `xrandr` to change brightness, which does not work with Wayland.

**Comment by FedeCuci** [comment]
You're right with the duplicate, sorry... Hope support for wayland is coming soon!
