### ISSUE TITLE
[Feature Request] Use DDC protocol to change backlight intensity of an external monitor

### ISSUE THREAD

**Issue by apandada1** [LordAmit/Brightness#180]
**Is your feature request related to a problem? Please describe.**

Right now, Brightness Controller changes the the colour of the screen and does not change the monitor's backlight. Having the ability to change the backlight would conserve electric power, with the added advantage of saving the eyes.

**Describe the solution you'd like**

Brightness Controller should be able to change the backlight level in both desktop and laptops, and it looks like it may be possible with [DDC protocol](https://en.wikipedia.org/wiki/Display_Data_Channel) and tools like `ddccontrol`

**Describe alternatives you've considered**

I found [this answer](https://askubuntu.com/a/548929/124466) in Ask Ubuntu, and was able to change the backlight intensity of my monitor connected to my **desktop** using the command line tool `ddccontrol` in Linux Mint 20. It has the same effect of changing the backlight intensity using the monitor's buttons. When I open the brightness settings in the monitor, it does show the updated brightness. I did not even know that the monitor backlight could be controlled in a desktop computer using software.

**Additional context**
We can still keep the current features, and implement a GUI for `ddcontrol` in an additional tab. I have only used the tool in my desktop so far. I have not checked how it works with a laptop's inbuilt monitor.

**Comment by LordAmit** [comment]
Interesting suggestion! 

The issue with DDC is that it is _only_ compatible with non laptop displays. 

> ddcutil does not support laptop displays, which are controlled using a special API, not I2C.

from https://www.ddcutil.com/

With the addition of it requiring additional configuration with respect to nVidia video drivers. Based on what you said, `ddc` should not be conflicting with `xrandr` - but some additional testing will be required.

**Comment by apandada1** [comment]
>The issue with DDC is that it is only compatible with non laptop displays.
Nowadays, the brightness function keys work out of the box in Ubuntu for most laptops.
It would very useful to be able to control desktop's backlight through software. I don't know if ddccontrol/ddcutil work with external monitor connected to laptop, if it does, it would be great.

**Comment by LordAmit** [comment]
> Nowadays, the brightness function keys work out of the box in Ubuntu for most laptops.

That's not something I decided :p DDC is the one who said the following explicitly in their website:

> ddcutil does not support laptop displays, which are controlled using a special API, not I2C.

> Nvidia's proprietary video driver may require special configuration. See Special Nvidia Driver Settings.
