### ISSUE TITLE
Brighness Controller closes suddenly

### ISSUE THREAD

**Issue by ReejeshPK** [LordAmit/Brightness#183]
I encounter a problem while using this in Ubuntu 18.04, the application stops suddenly and the brightness is back to normal again. I think it has something to do with ubuntu in handling the process. If there are any other things i can try kindly let me know.

**Comment by apandada1** [comment]
Are you using Redshift/Night Light? See #91

**Comment by ReejeshPK** [comment]
> Are you using Redshift/Night Light? See #91

Yes, I use Night Light, but application closes during the day also, not frequently, but occasionally.

**Comment by apandada1** [comment]
Try disabling Night Light (even during the day), and see if it works.

**Comment by ReejeshPK** [comment]
> Try disabling Night Light (even during the day), and see if it works.

Okay @apandada1 I will give that a try. Thanks.
