### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by Alex-Samari** [LordAmit/Brightness#184]
**Is your feature request related to a problem? Please describe.**
Application does NOT work on Wayland. Please provide support

**Comment by apandada1** [comment]
AFAIK, Wayland still does not have the backend for this. I had asked a question in Ask Ubuntu, which has not been answered yet.https://askubuntu.com/q/1286458/124466

**Comment by LordAmit** [comment]
Hello @Alex-Samari ! 

 `xrandr` is not supported in Wayland, and Brightness Controller only works for xrandr supporting systems as stated in the requirements. 

It is unfortunate, but unless Wayland offers a way to change brightness, we can not really do anything from our side.
