### ISSUE TITLE
missing libmkl_rt.so

### ISSUE THREAD

**Issue by matteodelucchi** [LordAmit/Brightness#187]
**Describe the bug**
`Intel MKL FATAL ERROR: Cannot load /home/<username>/anaconda3/lib/python3.7/site-packages/mkl/../../../libmkl_rt.so.
`

**To Reproduce**
1. Installed the requirements mentioned in the README manual installation section.
2. installed then via PPA following the README
3. tried to fire it up via shell and crashed with the above error

**Expected behavior**
normal start up

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by apandada1** [comment]
This must be a bug with MKL (Brightness Controller does not need to use any BLAS libraries, I have no idea why it popped up). Unless you really need MKL (it is [buggy](https://savannah.gnu.org/bugs/index.php?58926)), use OpenBLAS instead.

**Comment by matteodelucchi** [comment]
The directory I was in, was removed. `cd` to home could solve the error.
