### ISSUE TITLE
Brightness increases automatically after a while.

### ISSUE THREAD

**Issue by hafiz031** [LordAmit/Brightness#193]
**Bug description**
If you make the brightness lower, it will automatically increase after a while. This specially happens when you encounter some video being played on Facebook or LinkedIn. I experienced this specially in LinkedIn. I am currently using Firefox browser.

**To Reproduce**
1. Set the brightness to some lower level.
2. Open Friefox and visit LinkedIn.
3. Scroll down until a video arrives.
4. As the video starts the brightness will be increased.

**Expected behavior**
The brightness should not be changed automatically.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Google Chrome
 - Version: 91.0.4472.114 (Official Build) (64-bit)

**Device information:**
 - NVIDIA RTX 2060 Super; Driver:  NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3  
 - Display: ASUS VA229HR 21.5 full HD, IPS, 75 Hz, low blue light, flicker free, wall mountable monitor (HDMI, VGA, Audio speaker); Currently connected via HDMI.

**Note:**
I kept the Night Light option turned off on my machine.

**Comment by apandada1** [comment]
Please post the output of `xrandr -q`.

**Comment by hafiz031** [comment]
@apandada1 

Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 476mm x 268mm
   1920x1080     60.00*+  74.97    59.94    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1440x576      50.00  
   1440x480      59.94  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)

**Comment by apandada1** [comment]
Try the following. Close the Brightness Controller tool, and change brightness from the command line instead.
```
xrandr --output HDMI-0 --brightness 0.4
```

Can you reproduce the issue with LinkedIn?

**Comment by hafiz031** [comment]
@apandada1 yes I managed to reproduce it. Also please note that, I have changed the browser from Firefox to Chrome. I checked using the software and the command both. They both suffers from this issue. Also another important thing - this happens specially when you do the following: i. Turn on the PC, ii. Lower the brightness, iii. Visit LinkedIn and scroll until you see a video content (specially directly posted video, not any shared link).

**Comment by hafiz031** [comment]
@apandada1  another interesting thing, if you re-open the software, you will see the brightness slider is set to maximum level even if you previously moved the slider to set some lower brightness. Even if the brightness doesn't increase, the slider will be moved to the highest level automatically. Moreover the setting, doesn't sustain after you restart your PC. You have to re-set the brightness every time you start the PC (I mean it resets itself to the default settings, not to the last configured settings).

**Comment by apandada1** [comment]
> yes I managed to reproduce it
Then it is not our bug, as xrandr (the backend) also has the same issue. We can do nothing about that. It may be due to NVidia drivers. Check if changing the proprietary driver version helps.

> You have to re-set the brightness every time you start the PC

`File -> Save current as default`. It should save the settings.
