### ISSUE TITLE
Permission denied error after launching the application

### ISSUE THREAD

**Issue by arkaprovob** [LordAmit/Brightness#194]
Whenever I launch the application, it gives this error [Errno 13] Permission denied: '/home/<user>'; however, this does not affect the function because once I acknowledge the error, it starts and works as usual once I acknowledge the error.

**Comment by apandada1** [comment]
What OS are you using and how did you install the app?

There may be some issues with your permission settings. See https://stackoverflow.com/q/23870808/3128341
