### ISSUE TITLE
Please Help.

### ISSUE THREAD

**Issue by ituitis20-sesen19** [LordAmit/Brightness#196]
Hello, I am new to all this and can't figure this our myself. I have a couple of questions. Please explain me like I'm 5. 
1. How do I assign hotkeys to Brightness Controller? I just want to change the brightness using only my keyboard. 
2. How can I get Brightness Controller to launch at startup? 
3. How can I run Brightness Controller on the background? As I understood it should run on the background automatically, but it doesn't show up on taskbar and I don't think it is running when i close the tab. 

I am using Ubuntu 21.04, GNOME Version 3.38.5.  Thank you.

**Comment by apandada1** [comment]
1. Hotkeys are not implemented yet.
2. Check this out https://github.com/LordAmit/Brightness/issues/171
3. Right now, it does not run in the background. There was such a feature in the past, but it used deprecated APIs and we had to remove it in order to support recent versions of Ubuntu.

**Comment by ituitis20-sesen19** [comment]
Thank you very much, will hotkeys/running in the background available soon?

**Comment by apandada1** [comment]
> Thank you very much, will hotkeys/running in the background available soon?

We are quite busy, and cannot say when it would be available, but probably not anytime soon.
