### ISSUE TITLE
Brightness going back up after a few seconds

### ISSUE THREAD

**Issue by AdiWeit** [LordAmit/Brightness#197]
**Describe the bug**
The display brightness does go down, but a few seconds after releasing the slider "Brightness" of "Secondary" it goes up to the brightness it had before without moving the mouse after releasing the slider.

**To Reproduce**
1. Open the application (Brightness Controller)
2. turn down the scroller 'Secondary'

**Expected behavior**
The brightness is expected to stay where it was

**Desktop:**
 - OS: Linux Mint Cinnamon
 - Browser: Chrome
 - Version 20.1
 - application version: v2.3.4

I used the commands

> sudo add-apt-repository ppa:apandada1/brightness-controller
> sudo apt update
> sudo apt install brightness-controller

to install the package

**Comment by LordAmit** [comment]
Please check if you have Night Shift, Night Light, f.Lux, or anything like that installed.

**Comment by apandada1** [comment]
In LM Cinnamon, you might have redshift preinstalled. Disable that and try again.

**Comment by AdiWeit** [comment]
> In LM Cinnamon, you might have redshift preinstalled. Disable that and try again.

I didn't think about that, so thanks for the help! It works now, but is there any alternative to RedShift that can coexist? Otherwise it would be great to have a similar functionality in this application (at least like scheduling the settings for certain times)

**Comment by apandada1** [comment]
> at least like scheduling the settings for certain time

So far there is no such functionality in the app, and it may not be available in the near future (we are busy).
However, you may do this by setting up a cronjob which would execute appropriate xrandr commands (this app uses xrandr in the backend). See [this](https://askubuntu.com/a/62270/124466) for usage of xrandr.
