### ISSUE TITLE
App does not work on Ubuntu 21.04 hirsute

### ISSUE THREAD

**Issue by Salman-Asif** [LordAmit/Brightness#198]
Installed the app through CLI (Commands mentioned in the README.md)
On opening the Brightness Controller app and adjusting the brightness , nothing seems to happen.
Neither increase nor decrease happens. No settings including RGB changes seems to take affect.

**Comment by apandada1** [comment]
Possible duplicate of https://github.com/LordAmit/Brightness/issues/189
Switch to X.Org.

**Comment by Salman-Asif** [comment]
Yes I've read the other issue. I believe this was raised before and it's a duplicate. Closed the issue now.
Thanks :)
