### ISSUE TITLE
brightness-controller destroy the night light setting of ubuntu20.04

### ISSUE THREAD

**Issue by crazyn2** [LordAmit/Brightness#200]
**Describe the bug**
A clear and concise description of what the bug is. If the contents of the subsections do not apply, simply replace the contents with N/A.

**To Reproduce**
1. open the brightness-controller
2. Click on bar of brightness to control brightness of screen
3. See the night light of ubuntu disappeared and have to close the night light in settings of ubuntu system and reopen the night light

**Expected behavior**
the brightness of screen is changed and the night light is existing.

**Screenshots**
the screenshots could not demonstrate the difference.

**Desktop (please complete the following information):**
 - OS: Ubuntu20.04 x86_64

**Additional context**
By the way, the brightness-controller could not get the current brightness of the screen.Maybe it's the key to solve the problem

**Comment by apandada1** [comment]
They use different technologies in the backend, and are not compatible.

The workaround is to use one of them at a time.

Due to time constraints, it is not possible for us to rewrite brightness
controller at the moment.

**Comment by crazyn2** [comment]
Thank you. Maybe it's a temprorary solution by shell command.
```
dconf write /org/gnome/settings-daemon/plugins/color/night-light-enabled false
dconf write /org/gnome/settings-daemon/plugins/color/night-light-enabled true
```
