### ISSUE TITLE
Upgraded to Ubuntu 22.04 LTS and Brightness Controller won't work

### ISSUE THREAD

**Issue by sada-kubsad** [LordAmit/Brightness#206]
Hi

Had a fully functional Brightness Controller on Ubuntu 20.04 LTS. Upgraded to Ubuntu 22.04 LTS on release day. And now it does not work.

Both the Primary Brightness and Secondary Brightness are showing disabled. Tried to uninstall and reinstall Brightness Controller and problem persists. 

Here is my ouput from xrandr -q:
xrandr -q
Screen 0: minimum 16 x 16, current 1440 x 900, maximum 32767 x 32767
XWAYLAND0 connected primary 1440x900+0+0 (normal left inverted right x axis y axis) 330mm x 210mm
   1440x900      59.75*+
   1152x864      59.78  
   1024x768      59.68  
   800x600       59.47  
   640x480       59.38  
   320x240       59.52  
   1280x800      59.81  
   720x480       59.71  
   640x400       59.20  
   320x200       58.96  
   1368x768      59.71  
   1280x720      59.86  
   1024x576      59.58  
   864x486       59.45  
   720x400       59.55  
   640x350       58.91  

Thank you very much in advance.

Best Regards

Sada

**Comment by apandada1** [comment]
You seem to be using Wayland. This software only works on X.Org

**Comment by sada-kubsad** [comment]
Thank you. I disabled Wayland in Ubuntu 22.04 using[ these steps](https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop) and Brightness Controller works great.
