### ISSUE TITLE
Secondary controller disabled

### ISSUE THREAD

**Issue by Zyzer01** [LordAmit/Brightness#207]
The secondary controller seem not not be adjustable, but the primary controller works well.
![Screenshot from 2022-06-22 07-56-10](https://user-images.githubusercontent.com/82843086/174975576-7a2c1a00-31d6-49ab-b0d9-152bdcff6257.png)

**Comment by squarerootoftwo** [comment]
yes i am facing the same issue. Please someone help.

**Comment by Zyzer01** [comment]
I tried this, and it worked

`sudo gedit /etc/default/grub`

Change the following line 
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash" `
to

`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash acpi_osi=Linux acpi_backlight=vendor"`

`sudo update-grub`

And reboot
