### ISSUE TITLE
Is it possible to add a command line to control the brightness.

### ISSUE THREAD

**Issue by DemoorBug** [LordAmit/Brightness#208]
I want to control the brightness from the command line, so I can customize a lot of shortcuts

**Comment by apandada1** [comment]
We are using `xrandr` in the backend. You can use it to customize shortcuts. Here is a tutorial. https://linuxconfig.org/how-to-configure-your-monitors-with-xrandr-in-linux

**Comment by DemoorBug** [comment]
> We are using `xrandr` in the backend. You can use it to customize shortcuts. Here is a tutorial. https://linuxconfig.org/how-to-configure-your-monitors-with-xrandr-in-linux

Although this article does not mention setting the brightness.
But I found this: xrandr --output HDMI-1-1 --brightness 0.8.
Thank you.
