### ISSUE TITLE
Not able to clone on ubuntu 22.04

### ISSUE THREAD

**Issue by akshay2739** [LordAmit/Brightness#209]
![image](https://user-images.githubusercontent.com/58725613/177473710-244a90c0-a93d-4856-836e-b70bf811b729.png)

**Comment by apandada1** [comment]
What is the issue exactly?

**Comment by akshay2739** [comment]
using your instruction i am not able to install app on linux ubuntu 22.04

**Comment by apandada1** [comment]
Which all steps did you follow? And what was the output error?

Please add the steps in detail, otherwise we would not be able to help.

**Comment by akshay2739** [comment]
I have followed these steps 

`
sudo add-apt-repository ppa:apandada1/brightness-controller
sudo apt-get update
sudo apt-get install brightness-controller-simple
`

This is the error
![image](https://user-images.githubusercontent.com/58725613/177535315-283dd044-e0bb-495a-ad77-06a9d35b4bb4.png)

**Comment by apandada1** [comment]
Ok.

brightness-controller-simple was written in python2, which has been
deprecated.

We have discontinued the package in Ubuntu 22.04 because of missing
dependencies.
