### ISSUE TITLE
Doesn't work on Ubuntu 22.04.1 

### ISSUE THREAD

**Issue by stschirky** [LordAmit/Brightness#212]
I updated to ubuntu 22.04.1 LTS and can't get the tool to work anymore. The GUI works fine, it recognizes my screens, but it doesn't adjust the brightness anymore.

**Comment by LordAmit** [comment]
wayland?

**Comment by stschirky** [comment]
seems so

**Comment by apandada1** [comment]
Use X.Org instead. The backend (xrandr) used by this tool does not work with Wayland.

Duplicate of #189
