### ISSUE TITLE
Failing to build from the AUR

### ISSUE THREAD

**Issue by clankfish** [LordAmit/Brightness#216]
Hi, I've used this program in the past with no issues, reinstalled EndeavourOS today and went to install this but I'm getting this:

Installing from the AUR using the command "paru -S brightness-controller-git" I get:

==> Starting package()...
/home/pez/.cache/paru/clone/brightness-controller-git/PKGBUILD: line 40: cd: /home/pez/.cache/paru/clone/brightness-controller-git/src/brightness-controller/src: No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'brightness-controller-git-2.3.4.r286.ea7434a-2': 
error: packages failed to build: brightness-controller-git-2.3.4.r286.ea7434a-2

Any help would be greatly appreciated.

**Comment by clankfish** [comment]
Just realised you most likely aren't the maintainer of the AUR version, you can close the issue if I'm being dumb lol

**Comment by apandada1** [comment]
Recently we changed the structure of the source code and that's why the AUR is failing to build. We will try to coordinate with the AUR maintainer to fix it.

**Comment by clankfish** [comment]
Ah, I see! Thank you very much

**Comment by LordAmit** [comment]
Meanwhile, try the pip install method? (It is new!)

**Comment by apandada1** [comment]
The AUR package has been fixed. I verified that it works.
