### ISSUE TITLE
Ubuntu 22.04.01 - Slide bars not affecting brightness

### ISSUE THREAD

**Issue by Padmahas** [LordAmit/Brightness#217]
**Describe the bug**
I  upgraded Ubuntu from 20.04 to 22.04.01 (Didn't reinstall). The brightness controller which was working without any issues on 20.04 is now not working in Ubuntu 22.04.01. I even reinstalled brightness controller several times from "apt" repository. Still I can't get this to work.

**To Reproduce**
1. Upgrade Ubuntu from previous version to 22.04.01.
2. If brightness controller don't work, execute "sudo apt remove brightness-controller"
3. Add the brightness-controller ppa repository.
4. Reinstall by executing "sudo apt-get install brightness-controller"

**Expected behavior**
The Slider should have increased OR decreased the brightness of your monitor.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.01
 - Browser Firefox
 - Version 105.0.1

Just wondering how browser information will help here.

Is it is the problem with not completely removing brightness-controller? Which are the paths of brightness-controller related files to manually remove?

**Additional context**
Screen 0: minimum 16 x 16, current 1366 x 768, maximum 32767 x 32767
XWAYLAND0 connected 1360x768+0+0 (normal left inverted right x axis y axis) 410mm x 230mm
   1360x768      59.62*+
   1024x768      59.68  
   800x600       59.47  
   640x480       59.38  
   320x240       59.52  
   720x480       59.71  
   640x400       59.20  
   320x200       58.96  
   1280x720      59.65  
   1024x576      59.58  
   864x486       59.45  
   720x400       59.55  
   640x350       58.91  

Thank you.

**Comment by apandada1** [comment]
You are using Wayland. Logout and switch to X.Org in the login screen

**Comment by Padmahas** [comment]
@apandada1 That solved the issue.
Thank you very much.

**Comment by alexTitakoff** [comment]
Thanks, work!
