### ISSUE TITLE
sorry,my internet couldn't connect your software

### ISSUE THREAD

**Issue by haohao159-XD** [LordAmit/Brightness#223]
zhouzihao@zhouzihao-virtual-machine:~$ sudo apt-get install brightness-controller-simple
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 brightness-controller-simple

**Comment by LordAmit** [comment]
Can you please tell us what's going on? We can not read the non-English part, sorry!

**Comment by LordAmit** [comment]
@apandada1 , we probably need to change the readme description about the PPA. Can you please update it and send me a pull request? I was not aware that the simple version is not available anymore. (or maybe I was, and then I forgot!)

**Comment by apandada1** [comment]
Updated in #224
