### ISSUE TITLE
flatpak... is it possible?

### ISSUE THREAD

**Issue by fastrizwaan** [LordAmit/Brightness#228]
Hi Amit,

Thank you so much. Brightness control is a really useful feature.  Again, thank you it helps my eyes.

Also, could you consider brightness flatpak?

`pip install brightness-controller-linux` works!

**Comment by apandada1** [comment]
`pip` is available in every GNU/Linux distro, so flatpak is really not required.
However, if you can create a flatpak package and maintain it, you are welcome to do so :)

**Comment by LordAmit** [comment]
Hey @fastrizwaan , thanks for using Brightness Controller.

Our team does not have the expertise to create and maintain flatpak. 

However, if you are interested, you are very much welcome to join in and maintain the flatpak! :)
