### ISSUE TITLE
Brightness level is reset to max after releasing brightness fader

### ISSUE THREAD

**Issue by spiralspree** [LordAmit/Brightness#230]
I freshly installed the application according to the description. I choose my HDMI screen for the secondary screen in the drop-down menu, then grab the fader on the secondary screen's brightness slider, drag the fader downwards (screen brightness actually decreases but I experience heavy lagging in the app here), then release the fader with the mouse, and the brightness of the screen resets immediately to max (while the fader remains where I dragged it). It always happens so the app is useless like this.

**Comment by spiralspree** [comment]
Same happens when changing color profile. The screen changes for a moment, then immediately resets, while the faders are at the theoretical values. Tried disabling Slimbook Battery and restarting the machine too but it made no difference.

**Comment by spiralspree** [comment]
Running `xrandr --output HDMI-1-0 --brightness 0.75` from the terminal. Behaves the same (brightness is lowered for a moment, then reset to max immediately).

**Comment by apandada1** [comment]
Try disabling night light/redshift

**Comment by AlgorithmicAmoeba** [comment]
I have the same problem and to the best of my knowledge I do not have redshift installed and my night light setting is off. Is there a way to check what keeps changing the setting back?

**Comment by LordAmit** [comment]
@AlgorithmicAmoeba , realistically - there is no way for us to know what's going on at your machine. We know for certain that Brightness Controller either works or does not work, it does not have anything in its structure that results in resetting the Brightness.
