### ISSUE TITLE
Installation failure using yay.... failure occurred in build() [manjaro linux, gnome DE]

### ISSUE THREAD

**Issue by Kop3sh** [LordAmit/Brightness#232]
/home/username/miniconda3/bin/python: No module named build
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: brightness-controller-git

I use miniconda as the default python management tool
and I tried installing python-build and build packages using pip but it still does not work

**Comment by apandada1** [comment]
Can you ask a question on the AUR website instead? Alternatively, ask a
question on the Arch Linux forum
