### ISSUE TITLE
The brightness resets(or we can say the brightness is lost) to full brightness if there comes a new chat message in skype on the ubuntu-20.04. 

### ISSUE THREAD

**Issue by pavanyogi** [LordAmit/Brightness#234]
**Describe the bug**
The brightness resets(or we can say the brightness is lost) to full brightness if there comes a new chat message in skype on the ubuntu-20.04. 

**version**
Brightness Controller v2.3.4

**To Reproduce**
1. open the brightness controller, set the brightness as per your need, (actually i have added brightness controller to startup applications)
2. open the skype application and there should comes some message in the skype desktop app
3. As soon as there comes a chat notification from the skype app the brightness is lost

**Expected behavior**
The skype chat notification should not affect the brightness level set by this application. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu-20.04
 - Skype version 8.92.0.401
 - Version - Brightness Controller v2.3.4

**Additional context**
Add any other context about the problem here. Typically, the output of `xrandr -q`.

`xrandr -q when the brightness controller is working fine. 

```shell
xrandr -q
Screen 0: minimum 320 x 200, current 3840 x 2160, maximum 16384 x 16384
eDP-1 connected (normal left inverted right x axis y axis)
   1366x768      60.00 +
   1360x768      59.80    59.96  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 600mm x 340mm
   3840x2160     30.00*   30.00    25.00    24.00    29.97    23.98  
   2560x1440     59.95  
   1920x1080     60.00    50.00    59.94    30.00    24.00    29.97    23.98  
   1600x900      60.00  
   1280x1024     60.02  
   1280x800      59.91  
   1280x720      60.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
```

I will add the output of xrandr -q when the issue will happen again. 

xrandr -q output when skype notification removed the brightness:
```shell
xrandr -q
Screen 0: minimum 320 x 200, current 3840 x 2160, maximum 16384 x 16384
eDP-1 connected (normal left inverted right x axis y axis)
   1366x768      60.00 +
   1360x768      59.80    59.96  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 600mm x 340mm
   3840x2160     30.00*   30.00    25.00    24.00    29.97    23.98  
   2560x1440     59.95  
   1920x1080     60.00    50.00    59.94    30.00    24.00    29.97    23.98  
   1600x900      60.00  
   1280x1024     60.02  
   1280x800      59.91  
   1280x720      60.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
```
![Screenshot from 2023-01-18 12-31-38](https://user-images.githubusercontent.com/13834016/213105485-b69c6dfe-5478-4870-ad5f-82f36b7362fc.png)

Actually, I have saved the above screenshot settings as default settings and added the brightness controller to auto-start. It starts with system startup and the brightness controller takes control of screen brightness as per the default settings. After that, once I receive some skype chat message notification then the brightness is lost. I need to kill the brightness controller application and start it again.

**Comment by LordAmit** [comment]
Hi @pavanyogi, I am not sure if it is a bug in Brightness Controller or whether we can "fix" it. 

Brightness is a shared property that can be accessed by any number of applications e.g., Brightness Controller, Adaptive Brightness of Ubuntu/Linux, Night Shift, f.lux, and looks like Skype too). 

If any of the other, aggressive apps choose not to play nice and override existing brightness settings, Brightness Controller really can not gatekeep them away. Sure, we can think of a way that will result in Brightness Controller forcibly setting Brightness every 5 seconds or so, but that'd just result in a tug of war later on with an arbitrary number of applications trying to control Brightness, with unforeseen, unpredictable side effects. 

The simpler solution is just to disable the brightness resetting function of the aggressive app instead.

**Comment by pavanyogi** [comment]
We can possibly give the user the choice to restart the program. As a result, we can choose that menu choice to restart the brightness app whenever the brightness problem arises.

**Comment by apandada1** [comment]
` I need to kill the brightness controller application and start it again.` Does nothing happen when you change the brightness without closing the app?

**Comment by Pavanyogi121** [comment]
Yes, brightness control comes back if we change the brightness in the application. I have saved a specific settings as default settings. To get the same settings effect,  i prefer to close and relaunch the application instead of changing the brightness level.
