### ISSUE TITLE
ModuleNotFoundError: No module named 'brightness_controller_linux

### ISSUE THREAD

**Issue by devxbasit** [LordAmit/Brightness#242]
**Describe the bug**
The app does not open in Xubuntu 23.04 (Debian, XFCE)

**version**
latest via PPA repository For Ubuntu

**To Reproduce**
1. Open terminal, type `brightness-controller`, and hit  enter

**Screenshots**
![image](https://github.com/LordAmit/Brightness/assets/24441401/f582398f-e978-479d-89ce-e47945b6fdf1)

**Desktop (please complete the following information):**
![image](https://github.com/LordAmit/Brightness/assets/24441401/a405c06b-7397-43b9-9de7-2f48bd06c7a1)

**Additional context**

`Screen 0: minimum 320 x 200, current 2560 x 1080, maximum 16384 x 16384
eDP-1 connected (normal left inverted right x axis y axis)
   1366x768      59.99 +  40.00  
   1280x720      59.99  
   1024x768      59.99  
   960x720       59.99  
   928x696       59.99  
   896x672       59.99  
   1024x576      59.99  
   960x600       59.99  
   960x540       59.99  
   800x600       59.99  
   840x525       59.99  
   864x486       59.99  
   700x525       59.99  
   800x450       59.99  
   640x512       59.99  
   700x450       59.99  
   640x480       59.99  
   720x405       59.99  
   684x384       59.99  
   640x360       59.99  
   512x384       59.99  
   512x288       59.99  
   480x270       59.99  
   400x300       59.99  
   432x243       59.99  
   320x240       59.99  
   360x202       59.99  
   320x180       59.99  
HDMI-1 connected primary 2560x1080+0+0 (normal left inverted right x axis y axis) 798mm x 334mm
   2560x1080     59.98 +  74.99*   50.00  
   3840x2160     30.00    25.00    24.00    29.97    23.98  
   2560x1440     59.95  
   1920x1080     74.99    60.00    50.00    59.94  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.91  
   1152x864      75.00    59.97  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   832x624       74.55  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
DP-1 disconnected (normal left inverted right x axis y axis)
`

**Comment by apandada1** [comment]
Somehow, the wrongly packaged new version got pushed to 23.04. Downgrade with this deb package. I will soon revert the package in the ppa https://launchpad.net/~apandada1/+archive/ubuntu/brightness-controller/+files/brightness-controller_2.3.4-3~ubuntu22.10.1_all.deb
