### ISSUE TITLE
Make appimage format support

### ISSUE THREAD

**Issue by newyorkthink** [LordAmit/Brightness#245]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by archisman-panigrahi** [comment]
We don't have the capacity to maintain an appimage. If you (or someone else) build and maintain it, we will be happy to mention that in the readme.

**Comment by abhi-deshpande** [comment]
@LordAmit I have created an AppImage build for this app [here.](https://github.com/abhi-deshpande/Brightness/releases/tag/2.4) Could you please check and test it once ? I did not find any issues at my side. Please confirms if it works for you.

**Comment by newyorkthink** [comment]
> @LordAmit I have created an AppImage build for this app [here.](https://github.com/abhi-deshpande/Brightness/releases/tag/2.4) Could you please check and test it once ? I did not find any issues at my side. Please confirms if it works for you.我在这里为这个应用程序创建了一个 AppImage 版本[。](https://github.com/abhi-deshpande/Brightness/releases/tag/2.4)您能否检查并测试一次？我没有发现任何问题。请确认它是否适合您。

![image](https://github.com/user-attachments/assets/8ae3bff3-424a-47ae-aedd-9b5cb0b8db6a)

**Comment by abhi-deshpande** [comment]
@newyorkthink can you share your system information ? This seems to be a dependency issue. You can try installing/reinstalling `libxcb-xinerama0` with the command `sudo apt-get install libxcb-xinerama0` if you are on a Debian-based system.
