### ISSUE TITLE
Unable to add repository

### ISSUE THREAD

**Issue by 7--** [LordAmit/Brightness#246]
**Describe the bug**
$ sudo add-apt-repository ppa:apandada1/brightness-controller
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'

**version**
N/A

**To Reproduce**
enter command `sudo add-apt-repository ppa:apandada1/brightness-controller` on a new Debian 12 install. 

**Expected behavior**
repository added to apt

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 12

**Comment by archisman-panigrahi** [comment]
PPAs do not work on Debian. Instead, manually download the deb package from
launchpad and install it.

**Comment by 7--** [comment]
I installed brightness-controller_2.3.4-3~ubuntu22.04.1_all.deb but it's not working and the "Primary Brightness" is greyed out.
![image](https://github.com/LordAmit/Brightness/assets/4725003/52d1931a-9c02-4197-a065-cc8ebbf7c5dc)


I also tried these but not working either. 
https://ppa.launchpadcontent.net/apandada1/brightness-controller/ubuntu/pool/main/b/brightness-controller/?C=M;O=D
brightness-controller_2.3.4-2~ubuntu20.04.1_all.deb
brightness-controller_2.3.4-3~ubuntu22.04.1_all.deb
brightness-controller-simple_1.2.8-0~202002020713~ubuntu20.04.1_all.deb

I tried pip install but get 
```
 pip install brightness-controller-linux
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

**Comment by 7--** [comment]
Once I disabled Wayland it started working thanks. Working one I used Debian 12 https://ppa.launchpadcontent.net/apandada1/brightness-controller/ubuntu/pool/main/b/brightness-controller/brightness-controller_2.3.4-3~ubuntu22.04.1_all.deb
