### ISSUE TITLE
Can't pin to dock

### ISSUE THREAD

**Issue by 7--** [LordAmit/Brightness#247]
**Is your feature request related to a problem? Please describe.**
Can't pin to dock unless you add StartupWMClass=init.py to /usr/share/applications/brightness-controller.desktop

**Describe the solution you'd like**
somehow be able to pin to dock without having to edit .desktop file.

**Describe alternatives you've considered**
manually updating the .desktop file

**Additional context**
[Desktop Entry]
Name=Brightness Controller
Comment=Adjust your screen brightness easily
Icon=brightness-controller
Exec=/usr/share/brightness-controller/init.py
Terminal=false
Type=Application
Categories=Utility
StartupNotify=true
Name[en_US]=Brightness Controller
**StartupWMClass=init.py**

**Comment by archisman-panigrahi** [comment]
I will push a minor update to the PPA with the modified desktop file. Which dock are you using, by the way?

**Comment by archisman-panigrahi** [comment]
@7-- Can you test this deb package and let us know if it works as intended? If you confirm that it works, I will push it to the PPA. https://code.launchpad.net/~apandada1/+archive/ubuntu/brightness-testing/+build/27012648/+files/brightness-controller_2.3.4-4~ubuntu22.04.1_all.deb

**Comment by 7--** [comment]
It works great. I can pin without making any changes to .desktop file. 

I tried on my Debian 12 desktop and Ubuntu 22.04 laptop. Both had this issue before and are working now.

**Comment by archisman-panigrahi** [comment]
I have updated the PPA package with this modified .desktop file. This issue can be closed now.
