### ISSUE TITLE
Brightness controller has no effect

### ISSUE THREAD

**Issue by agnespeltan** [LordAmit/Brightness#252]
**Describe the bug**
Since update to ubuntu 22.04, the controls of Brightness Controller are not working. They have no effect whatsoever on the brightness of either my laptop screen or my external monitor.

**version**
Please include the version Brightness Controller you are using. 

**To Reproduce**
Open Brightness Controller
Tune the controls

**Expected behavior**
An effect on the screen brightness

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS

**Additional context**
xrandr -q
Screen 0: minimum 16 x 16, current 4480 x 1440, maximum 32767 x 32767
XWAYLAND2 connected primary 1920x1080+0+114 (normal left inverted right x axis y axis) 340mm x 190mm
   1920x1080     59.96*+
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77  
XWAYLAND4 connected 2560x1440+1920+0 (normal left inverted right x axis y axis) 530mm x 300mm
   2560x1440     59.91*+
   1920x1440     59.90  
   1600x1200     59.87  
   1440x1080     59.87  
   1400x1050     59.86  
   1280x1024     59.76  
   1280x960      59.94  
   1152x864      59.78  
   1024x768      59.68  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   1920x1200     59.88  
   1680x1050     59.85  
   1440x900      59.89  
   1280x800      59.81  
   720x480       59.71  
   640x400       59.20  
   320x200       58.96  
   2048x1152     59.90  
   1920x1080     59.88  
   1600x900      59.82  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.45  
   720x400       59.55  
   640x350       59.77

**Comment by archisman-panigrahi** [comment]
Are you using Wayland? Then switch from wayland to x11 (google how to).

**Comment by LordAmit** [comment]
```
XWAYLAND2 connected primary 1920x1080+0+114 (normal left inverted right x axis y axis) 340mm x 190mm
```

Looks like Wayland. Closing this unless this is not wayland!
