### ISSUE TITLE
Brightness Controller - version 2 GUI prototypes

### ISSUE THREAD

**Issue by lordamit** [lordamit/Brightness#43]
Hi,
Please check these out and let me know which one you prefer :dancer: 
# Type 1 - tabbed Interface

https://github.com/lordamit/Brightness/blob/prototypes/prototypes/Brightness_Controller_Test.png
# Type2 - Everything in one Interface

https://github.com/lordamit/Brightness/blob/prototypes/prototypes/Brightness_Controller_Test2.png

**Comment by matt32106** [comment]
the 2 links end up in 404, normal?

**Comment by lordamit** [comment]
Ah, yeah. We made our decision and moved to the new design interface. 

Forgot to close this.
