### ISSUE TITLE
Set default brightness on start up automatically?

### ISSUE THREAD

**Issue by zhongnanxu** [LordAmit/Brightness#46]
Is there a simple line to add to your .bashrc to automatically set the brightness on computer startup using this program? Thanks!

**Comment by FantaZZ** [comment]
So...   now...    These has some command line can be used ?

**Comment by mixrat** [comment]
Any progress on this? Is there a way to include an argument when starting from command line? It would be great to have this ability...

`$ brightness-controller -load '~/my-custom-settings'`

**Comment by gonesimera** [comment]
Is there any news on this?
thanks

**Comment by apandada1** [comment]
Now that #115 loads the default settings on startup of Brightness Controller (and the v2.1 in PPA contains that code), you can make a startup script that will run Brightness Controller, wait for a few milliseconds for the settings to load and close BC.

**Comment by LordAmit** [comment]
let us know if this works out for you @gonesimera , @FantaZZ , @mixrat , @zhongnanxu  :dancer:

**Comment by discon-nected** [comment]
Sorry for the late reply. This works great. I just added brightness-controller to my startup applications menu in Ubuntu. Cheers
