### ISSUE TITLE
System Tray Icon

### ISSUE THREAD

**Issue by shivams** [LordAmit/Brightness#49]
There should be a tray icon for the app. I've added that to the "trayicon" branch and sent a pull request.

**Comment by DavidPerezIngeniero** [comment]
When will it be integrated in the main branch?

**Comment by lordamit** [comment]
It won't, the changes he made were not complete and would raise more issues. 
I have closed the pull request and added details / works to be done for it to be accepted in the discussion of that particular pull request.
