### ISSUE TITLE
Saving the brightness setting

### ISSUE THREAD

**Issue by EasonWang01** [lordamit/Brightness#54]
Is it possible to saving brightness setting in the newest version?

**Comment by nicdevera** [comment]
Not really save, but you can set it up at startup. Search for Startup Applications, setup

xbacklight -set 5

and there, you've got a dim screen right after bootup.

**Comment by DavidPerezIngeniero** [comment]
`xbacklight` only serves for the primary display.
Use `xrandr` for more control.

**Comment by lordamit** [comment]
yes, it is possible to export the settings in a file and import from it.
