### ISSUE TITLE
[Linux Mint 17.3, Cinnamon 2.8] After setting the brightness and closing app the brightness level is not remembered

### ISSUE THREAD

**Issue by siemprepeligroso** [LordAmit/Brightness#56]
Run the app, set the desired brightness... Close the app, the brightness remains (visually) the same.
Run the app again, and the app does not remember the previously set brightness level.

Same happens if the monitor goes to sleep mode

**Comment by lordamit** [comment]
Indeed, currently it is not capable of remembering settings when being started. This should be taken care of soon.

**Comment by Aaahh** [comment]
The bigger problem is that if you lower the brightness, you cannot raise it once you close the app and reopen it, as the brightness bar shows 100%
It's not a matter of remembering settings, its reading the current settings

**Comment by apandada1** [comment]
Even if it wrongly shows 100%, it will work properly when you move the
slider.

**Comment by bhavybarca** [comment]
hi i would like to contribute to this issue.
P.S.-i am a beginner

**Comment by adamkoval** [comment]
Bump
