### ISSUE TITLE
Where is the app's icon?

### ISSUE THREAD

**Issue by koesherbacon** [LordAmit/Brightness#57]
I love, let me repeat, LOVE this package and have made it into a MATE applet as well as bound it to keyboard keys.  

What I'd like to know is where can I find Brightness' App Icon?  Whenever I launch it, the icon is totally fugly since it's just using the "no-icon" icon from my current icon theme.

Many thanks!

~ Ev

**Comment by lordamit** [comment]
Hi,
Maybe you are talking about this one?

https://github.com/lordamit/Brightness/blob/develop/img/brightness.svg?

BTW, are you using the old version or the currently being developed (really slowly) version?

**Comment by LordAmit** [comment]
:disappointed:  Closing this issue.
