### ISSUE TITLE
 Brightness Controller Stable Version not in Ubuntu Software Center after Ubuntu 14.04

### ISSUE THREAD

**Issue by lordamit** [lordamit/Brightness#58]
Self explanatory title ;)

**Comment by lordamit** [comment]
@apandada1 :ghost:

**Comment by apandada1** [comment]
![capture123](https://cloud.githubusercontent.com/assets/3063132/13905038/217db1a4-eeda-11e5-915f-dff6af7a5897.JPG)

Manual Debian packaging is like a nightmare and I don't even know all the steps. These pages even don't exist anymore. They won't accept .deb files that are not properly made but still just works.

**Comment by apandada1** [comment]
Ok, I will try this. http://askubuntu.com/questions/90764/how-do-i-create-a-deb-package-for-a-single-python-script

**Comment by lordamit** [comment]
Any update?

**Comment by apandada1** [comment]
Done. https://launchpad.net/~apandada1/+archive/ubuntu/brightness-controller
Will submit to software centre now.

**Comment by apandada1** [comment]
This should be closed this as Ubuntu Software Centre has been replaced by GNOME Software centre which does not support Proprietary and paid apps.
