### ISSUE TITLE
adding link to repository page in the website

### ISSUE THREAD

**Issue by lordamit** [lordamit/Brightness#62]
Hey Zlatan :ghost: 
@ZDroid 
![screenshot from 2016-04-11 02-08-13](https://cloud.githubusercontent.com/assets/480479/14412712/5d53b1cc-ff8a-11e5-908c-58d8d3c12dc1.png)

Does the last line look good?

**Comment by apandada1** [comment]
Also, should we declare that it actually is a constrast controller and does not dim backlight of a laptop (although it cannot be understood in desktops)?

**Comment by lordamit** [comment]
we are using xrandr to control the gamma values for computers which does not support hardware based brightness dimming.

For the version two, I am thinking about adding an actual brightness controller support based on hardware! :dancers:

**Comment by ZDroid** [comment]
It actually looks awesome. :+1:

**Comment by lordamit** [comment]
aaaaaand done!
