### ISSUE TITLE
not installable in xenial

### ISSUE THREAD

**Issue by lxle** [lordamit/Brightness#63]
error:dependency is not satifiable: python-wxgtk2.8

**Comment by apandada1** [comment]
​Looks like ​python-wxgtk2.8 is not available in Xenial. We need to
use python-wxgtk3.0
alternatively where available.

On Tue, Apr 26, 2016 at 6:01 AM, lxle <notifications@github.com> wrote:

> error:dependency is not satifiable: python-wxgtk2.8
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lordamit/Brightness/issues/63>
>



-- 
*Archisman Panigrahi. *

*I am learning Software Developing.*

*My Code: *https://github.com/apandada1/

*Supporting Greener Computing* - Do you really need to print this email?

**Comment by lordamit** [comment]
That's not exactly a bug, more a dependency based feature upgrade. 

Since we are focusing on v2, which is dependent on PySide - I will focus on that part. If someone wants to add python-wigth3.0 support to v1, he/she is more than welcome!

**Comment by lordamit** [comment]
But it has been fixed nevertheless by our @apandada1  Thank you! :ghost:

**Comment by apandada1** [comment]
This should be closed

**Comment by apandada1** [comment]
@lordamit  I think even v2 can be uploaded to PPA now. You can focus on finalizing it.

**Comment by lordamit** [comment]
Should be closed by the one who asked for support :smile:. 
V2 discussion should take place elsewhere. :dancer:

**Comment by lxle** [comment]
thanks
