### ISSUE TITLE
Labels in gui should be flipped

### ISSUE THREAD

**Issue by elmerehbi** [lordamit/Brightness#65]
Adjusting the primary/secondary brightness actually changes that of the external/internal monitor.

So I think they should be flipped in the gui.

And better named internal/external I guess?

**Comment by lordamit** [comment]
Hi,
You are most likely using version 1 of Brightness Controller. 

Sometimes xrandr misinterprets the primary and secondary monitor and flips it. Unfortunately, there is no way to detect that automatically.

However, it is possible to flip the switches. We introduced that facility in the version 2. Can you please try it from https://github.com/lordamit/Brightness ? Even though it is in beta, it is completely stable in terms of features. 

Please let us know.

**Comment by elmerehbi** [comment]
Spot on.

It works  as you suggested. Thanks.

Regarding the dependencies, for v2 is `wxgtk2.8` still required or just pyside?

**Comment by lordamit** [comment]
Just Pyside. Version 2 is a complete re write, removing the dependencies on wxWidgets.
