### ISSUE TITLE
Feature request: Set minimum brightness

### ISSUE THREAD

**Issue by elmerehbi** [lordamit/Brightness#68]
I think it would be good to set a minimum brightness to which one can reduce. I am not sure if this is the same as this [issue](https://github.com/lordamit/Brightness/issues/45).

It wouldn't be nice to loose sight of your desktop even if you have two screen enabled. Accidents could happen like switching to one screen only whose brightness is set to zero.

**Comment by apandada1** [comment]
It has happened to me twice recently and I had to manually restart the
computer as I could not remember the correct xrandr command.

@lordamit I can add a small file 'brightness-restore' to the source
and debian package, which will reset brightness when the command is
executed.

On 4/27/16, Ibrahim El Merehbi <notifications@github.com> wrote:
> I think it would be good to set a minimum brightness to which one can
> reduce. I am not sure if this is the same as this
> [issue](https://github.com/lordamit/Brightness/issues/45).
>
> It wouldn't be nice to loose sight of your desktop even if you have two
> screen enabled. Accidents could happen like switching to one screen only
> whose brightness is set to zero.
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lordamit/Brightness/issues/68


-- 
*Archisman Panigrahi. *

*I am learning Software Developing.*

*My Code: *https://github.com/apandada1/

*Supporting Greener Computing* - Do you really need to print this email?
