### ISSUE TITLE
app doesn't work

### ISSUE THREAD

**Issue by amschatz** [lordamit/Brightness#70]
I recently had to restart my computer, and once that was done, the app no longer worked. I've uninstalled and reinstalled twice now. When I move the brightness slider down, the screen flickers to the appropriate dimness and then immediately returns to full brightness. I'm working on a two-monitor set-up, both Dells. The computer is ubuntu 14.04 LTS.

**Comment by lordamit** [comment]
Hmm.. 
what happens when you use xrandr to change brightness from terminal?

**Comment by lordamit** [comment]
Due to lack of information, this issue is closed now.
