### ISSUE TITLE
Nuke excess branches (?)

### ISSUE THREAD

**Issue by zdroid** [lordamit/Brightness#71]
`prototypes`, `installers`, `html` are unused branches, I think it's a good idea to nuke them and eventually merge anything useful from them to the main branch. Now, back to the main branch, wouldn't it be more useful to merge `develop` and `master`? It'd be way easier to maintain the project with only one branch.

**Comment by lordamit** [comment]
`html` is the html version of the same application experimentally by @apandada1 . Lets see what he has in his mind. 

`prototype` is the experimental branch - so it can be nuked. 

`installers` - will be nuked.

`develop` and `master` will be merged.

**Comment by zdroid** [comment]
Good to hear that @lordamit. :+1:

**Comment by zdroid** [comment]
@lordamit Are there any critical merging issues between develop and master?

**Comment by apandada1** [comment]
I think there will be issues while merging. Things we can do
1. Rename Master as v1(discontinued) and develop as master
2. Delete current master branch and rename develop as master.
3. Replace Master Branch with develop branch.

**Comment by zdroid** [comment]
@apandada1 We can do the third option, but the most important changes should be manually applied to develop before renaming.

**Comment by lordamit** [comment]
For preserving history, we should be keeping the master as v1. Develop will be renamed as master.
Sounds good?

**Comment by zdroid** [comment]
Sounds good enough to me @lordamit.

**Comment by zdroid** [comment]
Another good change would be to put `gh-pages` into `docs/` directory on master branch, as GitHub allows us to build sites from there, too.

**Comment by lordamit** [comment]
That will mean downloading the master repository with the website. Why should user bother about that when he only wants to go through the sources?

**Comment by zdroid** [comment]
Alright @lordamit, agreed. :+1:

**Comment by lordamit** [comment]
Changes are applied. There are not 3 branches: 

- master (old develop)
- v1 (old master)
- gh-pages

**Comment by zdroid** [comment]
Good work. :tada:

**Comment by apandada1** [comment]
@LordAmit `add-code-of-conduct-1` and probably `mockup` can be deleted.
