### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by smonff** [lordamit/Brightness#73]
I use Brightness on ArchLinux since quite a long time. Since today, Brightness crashes at launch with this message:

    $ brightness   
    Traceback (most recent call last):
        File "/usr/lib/brightness/init.py", line 19, in <module>
            from PySide import QtGui, QtCore
    ImportError: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

I guess it it related to some dependency upgrade.

**Comment by smonff** [comment]
This problem was caused by `freetype2-infinality`. Not related to Brightness. Everybody using this should switch to `freetype2` as they merged infinality features.

**Comment by lordamit** [comment]
Thank you for letting us know! :smile:
