### ISSUE TITLE
Good for the eyes: yes, good for power usage: ?

### ISSUE THREAD

**Issue by matt32106** [LordAmit/Brightness#74]
This addon is a blessing for my eyes as i can now set the brightness easily without playing with the monitor dumb interface (where are the good old knobs?). 
I would like to know if it also is good for the planet - and your electricity bill, i.e. does it cut power usage? 
If no, is it possible to put that as as goal?

Thanks

**Comment by lordamit** [comment]
Hi Matt,
I am really glad to know that you found Brightness Controller useful! :) 
As far as I understand, it does not cut power usage; and due to the feature's hardware based nature, it will be really complex and difficult.
