### ISSUE TITLE
Brightness controller is not working

### ISSUE THREAD

**Issue by dimxx** [LordAmit/Brightness#75]
Good evening. Brightness controller is not working for me in ubuntu 14.04 lts. I install the app with terminal and download it from here and unpack files. I see it in the left bar of icons, doing double click and appears the app on the desktop. I slide the line with mouse left-right but do nothing.   My desktop have: 
                                                   memory: 7,0 GiB
                                                   Processor: AMD A10-6790K APU with Radeon(tm) HD Graphics × 4
                                                   graphics: Gallium 0.4 on llvmpipe (LLVM 3.6, 128 bits)
                                                   64-bit  &  hard drive 629,7 GB

**Comment by lordamit** [comment]
Hi!

Can you please provide the output when you enter `xrandr` in terminal?

**Comment by LordAmit** [comment]
Closing this due to lack of information :disappointed:
