### ISSUE TITLE
Implementing Changes and Saves version 2 bug

### ISSUE THREAD

**Issue by xSeekTruthx** [LordAmit/Brightness#80]
@apandada1
Tested v 2 on Ubuntu 14.04 - 3 monitors.

Everything works "after you re-activate the drop down menus and change
slider position"

For anything to work in Primary or Secondary sliders, I must re select
Primary or Secondary sources from the drop down.

This applies to loading the saved settings as well.
- It changes the slider positions, however does not implement the change
until a drop down is selected, and a new position on the slider is selected.

Playing with the RGB is fun, and the previous blue color looked nice as
well.
---
@xSeekTruthx I am using the latest source from
`lordamit/Brightness/master`. So this issue should be present in this
branch as well. Is it so?

Bye the way, I wrongly packaged it v2.1, should be v2.
---
@apandada1 Yes. This is just my first time giving full test feedback on v 2.

**Comment by LordAmit** [comment]
Hey, @xSeekTruthx .
The color actually depends on your theme. So, depending on your theme - it will change its color. 
About the load settings - forgot to implement it :monkey:

**Comment by LordAmit** [comment]
Hey @xSeekTruthx, I have checked and fixed it. Can you please check? :smile:

**Comment by xSeekTruthx** [comment]
Perfect for 2 Monitors. Once settings are set, able to save, and re load back to original, then applies settings without issue. 
- Does not retain settings for more than 2 monitors.

**Comment by LordAmit** [comment]
Great! Please close this issue, as this is now solved. :man_dancing:
