### ISSUE TITLE
Settings snap back to original level

### ISSUE THREAD

**Issue by SteveWooding** [LordAmit/Brightness#91]
OS: Linux
Distro: Ubuntu 17.04
output of `xrandr -q`

```
Screen 0: minimum 8 x 8, current 3600 x 1080, maximum 16384 x 16384
VGA-0 disconnected (normal left inverted right x axis y axis)
DVI-D-0 connected primary 1920x1080+1680+0 (normal left inverted right x axis y axis) 531mm x 299mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
HDMI-0 connected 1680x1050+0+0 (normal left inverted right x axis y axis) 474mm x 296mm
   1680x1050     59.88*+  59.95  
   1600x1200     60.00  
   1440x900      74.98    59.89  
   1280x1024     75.02    60.02  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
```

Version of Brightness Controller: v2.0 build 1

Hello. Here's the issue: When I move any slider, the setting is applied for a brief period (around half a second) before reverting to what is was before. So for example, I move the brightness slider to 50%. The screen dims briefly, then immediately goes back to what it was before. Same issue on two completely different monitors.

I'm using the Nvidia proprietary driver. Maybe that is the issue?

Thanks,

Steve Wooding.

**Comment by LordAmit** [comment]
hi,
Are you using any color temperature related software, like redshift?

**Comment by SteveWooding** [comment]
Hi Amit,

Great catch. Yes I was (f.lux). I stopped it running and your program is working fine now. Nice level of control. May use it instead of f.lux.

Sorry to have bothered you with this.

Cheers,

Steve.

**Comment by LordAmit** [comment]
Hey Steve,

No worries! :+1: Really glad that this was easily solved. If you like it, share and star :wink:
