### ISSUE TITLE
No make instructions

### ISSUE THREAD

**Issue by gnanini** [LordAmit/Brightness#92]
OS: Arch Linux
Distro: Arch Linux
output of `xrandr -q`
Version of Brightness Controller: 

I don't need to put my xrand -q output because I just want the dependencies list and a ./configure script.

Thanks!

**Comment by LordAmit** [comment]
Hi,
I don't know how to make the .configure script :disappointed: 
But I can provide the dependencies list. Will that be Okay?

Also, may I know why you need a make instruction when you can install the dependencies, download, unzip and then run the script? (unless the installation of dependencies is somewhat different in Arch? No idea to be honest. )

**Comment by gnanini** [comment]
It was impossible to run the script because a or some dependencies are missing! 

Yes, I want the list of dependencies.

By the way, It's a great idea, I'm eager to see your software running. I will test it soon on ubuntu!

**Comment by LordAmit** [comment]
Hmm, you need python version 2, python-pyside first of all. Did you install these? 
Also, what happens when you try to run the app from terminal? Like this:
```
python src/init.py
```

**Comment by gnanini** [comment]
perfect!!!

I installed the dependence python2-pyside and I ran python2 src/init.py

Thanks!!

**Comment by LordAmit** [comment]
Glad to know :smile:
