### ISSUE TITLE
Add saturation functions

### ISSUE THREAD

**Issue by Ygarr** [LordAmit/Brightness#94]
Ability to decrease colors to greyscale, black and white

OS: Linux 
Distro: Debian Sid 9
output of `xrandr -q`:
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
HDMI-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  

Version of Brightness Controller: where

**Comment by LordAmit** [comment]
Umm, 
That will probably be a bit out of xrandr's capacity. Since that's what we use as the backend of Brightness Controller - we might not be able to implement it. We will keep that in mind in next release cycle, however :)
