### ISSUE TITLE
Something to consider using

### ISSUE THREAD

**Issue by maandree** [LordAmit/Brightness#95]
Your project would benefit a lot from using libcoopgamma:
C library: https://github.com/maandree/libcoopgamma/
Python binding: https://github.com/maandree/pylibcoopgamma/
Daemon: https://github.com/maandree/coopgammad
Programs using libcoopgamma: https://github.com/maandree/cg-tools/
Library the first library depends on: https://github.com/maandree/libgamma

**Comment by LordAmit** [comment]
Hi!

Thanks, we will check it out :)
