### ISSUE TITLE
primary and secondary displays disabled

### ISSUE THREAD

**Issue by dineshraj01** [LordAmit/Brightness#96]
OS: ubuntu 16.04
Distro: gnome
Screen 0: minimum 320 x 200, current 1366 x 768, maximum 8192 x 8192
eDP-1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1366x768      60.03*+  40.01  
   1360x768      59.80    59.96  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   960x600       60.00  
   960x540       59.99  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   800x512       60.17  
   700x525       59.98  
   640x512       60.02  
   720x450       59.89  
   640x480       60.00    59.94  
   680x384       59.80    59.96  
   576x432       60.06  
   512x384       60.00  
   400x300       60.32    56.34  
   320x240       60.05  
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)

Version of Brightness Controller:  2

Cannot change the brightness, says primary display disabled. I have attached a screenshot.

![screenshot from 2017-06-23 10-24-07](https://user-images.githubusercontent.com/14002943/27467301-ef6e8f64-57fe-11e7-90af-e74d321f1ac0.png)

**Comment by LordAmit** [comment]
Hi, the drop downs are supposed to be disabled when you have only one display. 
What happens when you use the sliders?

**Comment by dineshraj01** [comment]
Brightness changes momentarily and then comes back to what it was earlier.

**Comment by dineshraj01** [comment]
I have also tried chaning color temperature. It changes for an instant and jumps back to original again.

**Comment by LordAmit** [comment]
You are probably using f.lux/redshift/Night Light in your OS. Those software can override the settings of Brightness Controller.

**Comment by dineshraj01** [comment]
I found flux was installed on my system. Removed it, rebooted and brightness controller is working.
Thanks man 👍

**Comment by LordAmit** [comment]
:) Glad to help.
