### ISSUE TITLE
brightness controller not working for me, i can change primary brightness bar but nothings happening

### ISSUE THREAD

**Issue by deepak2215** [LordAmit/Brightness#97]
OS: linux
Distro: ubuntu 17.04

output of `xrandr -q`
xrandr: Failed to get size of gamma for output default
Screen 0: minimum 1366 x 768, current 1366 x 768, maximum 1366 x 768
default connected primary 1366x768+0+0 0mm x 0mm
   1366x768      76.00* 

Version of Brightness Controller:  version 2.0 build 1

and i've added nomodeset in grub may be its happening because of this

**Comment by LordAmit** [comment]
Hi Deepak,
It seems like xrandr can not detect the name of the device/can not detect the connected device - although it can show the resolutions.
Also, it is failing to get the size of gamma for output default.

I am not sure why this is happening at your part, but if your display can not get detected(which is outside the scope of this software, unfortunately) I can not really help you. :disappointed:
