### ISSUE TITLE
Notes on installation (Debian).

### ISSUE THREAD

**Issue by Achaean** [LordAmit/Brightness#98]
OS:  Linux.
Distro: Debian Jessie (oldstable) x64 KDE.
output of `xrandr -q`
```
Screen 0: minimum 320 x 200, current 1360 x 768, maximum 16384 x 16384
DFP1 disconnected (normal left inverted right x axis y axis)
DFP2 disconnected (normal left inverted right x axis y axis)
CRT1 connected primary 1360x768+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1600x1200     60.00 +
   1400x1050     60.00
   1600x900      60.00
   1280x1024     60.02
   1440x900      59.89
   1280x960      60.00
   1366x768      59.79
   1360x768      60.02*
   1280x800      59.81
   1152x864      60.00
   1280x768      59.87
   1280x720      60.00
   1024x768      60.00
   800x600       60.32
   720x480       60.00
   640x480       59.94
```
Version of Brightness Controller:  2.0b1.

**Hi!**  :-)

Just a couple of suggestions here, for Debian users.
1) Installing python-pyside from repositories didn't work for me. I'm suggesting to skip this step and proceed installing pyside with pip.

2) Install pyside as root.
("su -" and then "pip install pyside").
Otherwise you have to configure pip to install at user basis, or it will fail.

3) Run (as root)  "pip install pyside" and look at the terminal the 1st stage of execution (before the actual building).
Don't mind the QT "not found" messages for Windows, embedded Linux etc. You only need the X interface.
Most important look for prerequisites.
If you see any needed package that didn't found, when the actual build starts, press ^C and break the compilation.
Open Synaptic (or install any way you like eg. with "apt install" ) and install the missing dependencies.
At my own system, I had to install "python-libxslt", "libxslt1-dev", "libxml2-dev" and "python-sphinx".

4) Run again "pip install pyside" and double check that you met all requirements.
If not, install what is missing.
If everything's perfect.......press ^C and break again! :-)
(Don't break if you have a single core processor. Just wait).

5) Give "pip install --install-option="--jobs=N" pyside" (where N is your number of processor cores).
Eg. I have a quad-core AMD, so I gave "pip install --install-option="--jobs=4" pyside".

This way, the process, will significantly speed up (taking advantage of the power of modern CPUs).

Well....what actually has to say, is maybe is a good idea such a mini-guide to be posted at the front page's README, so everyone can benefit from this wonderful piece of software! ;-)

**PS.** I'm not any kind of Python expert! Feel free to edit-correct these notes.

Last but not least, **many thanks** and **congrats** to the authors!!! :-)
A.

**Comment by LordAmit** [comment]
Hey, thanks! 

Will be linked to the readme file directly after a while :) 

I hope you are enjoying using the Brightness Controller after going through all those steps of installation and was worth it.

**Comment by Achaean** [comment]
**THANKS!!!** :-)
